### ISSUE TITLE
Cumulative ongoing

### ISSUE THREAD

**Issue by Mice73** [elastic/timelion#100]
Hi,
I need to get into a time the unique occurrence of a given name.
So if the name occurs the first day and next one, I've to get the first one.
If a name arrive a day 3, I've to take this at this day.
The names have to be count only one time, so I've a cumulative but on first occurrence of each name.
Is this possible?

**Comment by rashidkpc** [comment]
This is not possible, timelion only handles numbers and timestamps, and none of the existing data stores that it supports can do this as far as I know.
