### ISSUE TITLE
Series expression editor

### ISSUE THREAD

**Issue by pagenbag** [elastic/timelion#103]
I'm wondering , since the series expressions can get rather long (especially if you have multiple series) , if its not worth having an edit button , which could open the expression in a bigger text-editor style area ? 

A popup is probably easiest , but an expanding area (something like Kibanas filter editor) is probably better. ? Maybe even create a syntax highlighter for ace ?

**Comment by pagenbag** [comment]
Something along these lines ? 

![image](https://cloud.githubusercontent.com/assets/8225423/14647261/31e62946-065d-11e6-878f-b2ada7532cd6.png)

then 

![image](https://cloud.githubusercontent.com/assets/8225423/14647267/3645c5be-065d-11e6-801a-5b8e2ce08042.png)

Some inherited CSS ?flex stuff? is messing me around. Had to set width:100% !important , just to get it to display :O

**Comment by rashidkpc** [comment]
Yeah, I'd love to build in an ace editor with syntax highlighting and such, would be ultra cool.

**Comment by pagenbag** [comment]
Cool - when I have some more time , I'll try and get it working. The CSS is just messing me around (I'm actually a C++ developer).

**Comment by rashidkpc** [comment]
Since https://github.com/elastic/timelion/issues/31 already has some discussion, I'm going to close this and move discussion over there.
