### ISSUE TITLE
Dashboard Visualization Not Filterable

### ISSUE THREAD

**Issue by WarriorOfWire** [elastic/timelion#104]
![screen shot 2016-04-19 at 9 49 56 am](https://cloud.githubusercontent.com/assets/3454741/14647849/6476bfc2-0614-11e6-8963-e90ff66ec571.png)

Collecting data from a distributed application, sometimes I need to view dashboards for a subset of metrics reporters.  This works great in vanilla Kibana visualizations, but the awesome Timelion charts are missing the simple search box filter functionality that is richly idiomatic on the dashboard.

**Comment by rashidkpc** [comment]
Due up https://github.com/elastic/timelion/issues/80
