### ISSUE TITLE
RRD datasource

### ISSUE THREAD

**Issue by pagenbag** [elastic/timelion#105]
I created a datasource for rrd(tool) , and all seems to be working... though I still need to add some error handling.

However , the node.js binding for rrd (https://www.npmjs.com/package/rrdjs#rrdjsfetchfile-start-end-step-callback) that I used , node gyp builds/links some c libs. 
Not sure how something like that is handled. Will the kibana plugin installer take care of rebuilding dependencies ?

**Comment by rashidkpc** [comment]
Unfortunately you can't use anything that needs c libraries in Kibana plugins. We haven't completely sorted out platform specific plugins yet and we don't want people to need build tools on their production boxes.

**Comment by pagenbag** [comment]
Ah ok - Well, it was more of a fun little test for me. We are specifically looking at moving our RRD data into elasticsearch ; So we wont have much use for it - was jsut a good way to verify the data - and since RRD Is still relatively popular in timeseries world , I thought there might be use for it.

There is a non-c rrd lib (https://www.npmjs.com/package/rrdtool) which I initially used - but I couldnt get it working properly (always returned NaNs)

**Comment by rashidkpc** [comment]
Yeah, the RRD file format is architecture dependent, its super hard to create a portable RRD reading library. I don't think its really even possible to create a generic implementation.

**Comment by pagenbag** [comment]
Then I'll just close this for now ... until someone has an actual need/request for rrd datasource.
