### ISSUE TITLE
Timelion: Error: in cell #1: Cannot read property 'es' of undefined

### ISSUE THREAD

**Issue by Doweig** [elastic/timelion#107]
Hello guys,

I wanna start by saying that Kibana and ES are awesome, we use it in combination on statsd to count everything that's possible to count, and we are very happy about it 👍 
You guys are doing an awesome job!

I just installed timelion and it doesn't seems to work, I get this error:

![screen shot 2016-04-28 at 11 49 06 am](https://cloud.githubusercontent.com/assets/1850848/14874877/4200b84c-0d37-11e6-9ef4-6cfe08816eff.png)

Can't get any graphs out of it, any ideas?

PS:
I run on Chrome 51.0.2704.22 
Kibana 4.5.0 is running on Nodejs 4.4.1
JVM: 1.7.0_95 ES: 2.3.1

Thanks, :)

**Comment by rashidkpc** [comment]
Bad commit, fixed here: https://github.com/elastic/timelion/commit/46788cc7ec004f182a300b42c5a0153605b78f8c

**Comment by rashidkpc** [comment]
Remove timelion and re-install and you should be good to go
