### ISSUE TITLE
Unable to install Timelion on windows 

### ISSUE THREAD

**Issue by deeparora** [elastic/timelion#110]
Hi 

I am getting this error while running Kibana with installed timelion plugin in Windows machine

Optimizations failure.\n\n    ERROR in ../installedPlugins/timelion/public/app.js\n    Module build failed: SyntaxError: D:/Elasticsearch/kibana-4.4.2-windows/installedPlugins/timelion/public/app.js: Unexpected token (3:0)\n      1 | var _ = require('lodash');\n      2 | var logoUrl = require('./logo.png');\n    > 3 | <<<<<<< HEAD\n        | ^\n      4 | =======\n      5 | var configFile = require('../timelion.json');\n      6 | var moment = require('moment-timezone');\n        at Parser.pp.raise (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\location.js:24:13)\n        at Parser.pp.unexpected (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\util.js:82:8)\n        at Parser.pp.parseExprAtom (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\expression.js:425:12)\n        at Parser.pp.parseExprSubscripts (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\expression.js:236:19)\n        at Parser.pp.parseMaybeUnary (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\expression.js:217:19)\n        at Parser.pp.parseExprOps (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\expression.js:163:19)\n        at Parser.pp.parseMaybeConditional (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\expression.js:145:19)\n        at Parser.pp.parseMaybeAssign (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\expression.js:112:19)\n        at Parser.pp.parseExpression (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\expression.js:79:19)\n        at Parser.pp.parseStatement (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\statement.js:137:23)\n        at Parser.pp.parseTopLevel (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\statement.js:30:21)\n        at Parser.parse (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\parser\\index.js:70:17)\n        at Object.parse (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\node_modules\\babylon\\lib\\index.js:45:50)\n        at Object.exports.default (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\lib\\helpers\\parse.js:36:18)\n        at File.parse (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\lib\\transformation\\file\\index.js:574:40)\n        at File.parseCode (D:\\Elasticsearch\\kibana-4.4.2-windows\\node_modules\\babel-core\\lib\\transformation\\file\\index.js:691:20)\n     @ ../optimize/bundles/timelion.entry.js 24:0-31\n",

Thanks
Deepak Arora

**Comment by rashidkpc** [comment]
Fixed: https://github.com/elastic/timelion/issues/109
