### ISSUE TITLE
Issue on displaying the timeseries visualization in Kibana

### ISSUE THREAD

**Issue by deeparora** [elastic/timelion#114]
Hi,

I am getting the javascript error while running the time series visualization in Kibana in the attached screenshot. In Timelion GUI, it's working fine.
![screen_timeseries](https://cloud.githubusercontent.com/assets/14983268/14951219/f18d5e2e-1074-11e6-8c36-e00a5c1fc08c.jpg)

Thanks
Deepak Arora

**Comment by rashidkpc** [comment]
Uninstall and re-install, this was fixed on Friday: https://github.com/elastic/timelion/commit/f7a7357ed661f307274be3f8d2a56b6ab2e906f8
