### ISSUE TITLE
Unknown provider: savedSheetsProvider <- savedSheets error in timelion 5.0.0-alpha2

### ISSUE THREAD

**Issue by ycombinator** [elastic/timelion#115]
Downloaded Kibana 5.0.0-alpha2 and installed Timelion like so:

`./bin/kibana-plugin install timelion`

When I load up the Timelion app in Kibana, I get a blank page. The developer tools console in Chrome shows this error:

```
commons.bundle.js?v=12279:38 Error: [$injector:unpr] Unknown provider: savedSheetsProvider <- savedSheets
http://errors.angularjs.org/1.4.7/$injector/unpr?p0=savedSheetsProvider%20%3C-%20savedSheets
    at commons.bundle.js?v=12279:35
    at commons.bundle.js?v=12279:36
    at Object.getService [as get] (commons.bundle.js?v=12279:36)
    at commons.bundle.js?v=12279:36
    at getService (commons.bundle.js?v=12279:36)
    at Object.invoke (commons.bundle.js?v=12279:36)
    at commons.bundle.js?v=12279:85
    at processQueue (commons.bundle.js?v=12279:38)
    at commons.bundle.js?v=12279:38
    at Scope.$eval (commons.bundle.js?v=12279:39)
```

**Comment by rashidkpc** [comment]
Unfortunately I have to ask:

*Which 5.0.0-alpha2?* As in, when did you run that command? Just now?

The way the plugin system is designed, the version string attached to the plugin is not the actual version of the plugin, rather the version of kibana (and Elasticsearch).

**Comment by ycombinator** [comment]
> Which 5.0.0-alpha2? As in, when did you run that command? Just now?

Yes, right before creating this issue, so about 4 hours ago. If it helps, I looked at the `version` in `installedPlugins/timelion/package.json` and its value is `5.0.0-0.1.287`.

**Comment by ycombinator** [comment]
Just uninstalled and reinstalled timelion. The new version is `5.0.0-0.1.289`. It does not have this issue any more. Thanks @rashidkpc!
