### ISSUE TITLE
I get this error when I access Timelion on Kibana

### ISSUE THREAD

**Issue by OElesin** [elastic/timelion#116]
I get this error from my browser when I access Timelion 
`Uncaught TypeError: __webpack_require__(...).enable is not a function (http://localhost:5601/bundles/timelion.bundle.js:78214)`

**Comment by rashidkpc** [comment]
Version information?

**Comment by harishbsrinivas** [comment]
+1 on this. I faced the same problem today.
my kibana version information is below
Version 	4.3.0
Build 	9369
Commit SHA 	e32749e

**Comment by OElesin** [comment]
I get the same error on Kibana 4.5.0 as well as Kibana 5.0 alpha2

**Comment by rashidkpc** [comment]
@harishbsrinivas timelion is not supported on 4.3.0, see the README.md

**Comment by rashidkpc** [comment]
@OElesin are you restarting kibana after installing?

**Comment by rashidkpc** [comment]
Closing for lack of feedback. I'm going to assume this is resolved.

**Comment by harishbsrinivas** [comment]
I upgraded to the latest version of kibana 4.5.0, this works perfectly fine.
