### ISSUE TITLE
Using multi timefields on timelion

### ISSUE THREAD

**Issue by yuvalzaltz** [elastic/timelion#117]
Hi

Is there an option to use 2 or more timefields in the same timelion sheet?

for example i would like to have one chart based on creation date and the other on last updated date ? 

Thanks!

**Comment by rashidkpc** [comment]
`.es(timefield=CREATION_DATE), .es(timefield=UPDATED_DATE)`

**Comment by yuvalzaltz** [comment]
Thank you!
