### ISSUE TITLE
.es(kibana=true) does not work with dashboard query input

### ISSUE THREAD

**Issue by WarriorOfWire** [elastic/timelion#124]
Kibana version: 9889
Timelion version: 4.5.0-0.1.323

1. Save a valid Timelion visualization.
2. Go to a new dashboard and place that Timelion visualization on the dashboard.
3. Add Kibana dashboard filter like `nonexistent:nonexistent`

Expected:  Chart should be empty since we queried for nonexistent data.
Observe that the filter is not applied and the previous default `*` filtration is still in effect.

Installed correctly following instructions, restarted Kibana, refreshed browser (also tried incognito); the POST from the `run` event for Timelion doesn't include the filter in `extended.es.filters` at all.

> {"sheet":[".es(index=\"my_index*\", q=\"returns:data\", metric=\"avg:millis\",kibana=true)"],
>   "extended":{"es":{"filters":[]}},
>   "time":{"from":"now-15m","interval":"10s","mode":"quick","timezone":"UTC","to":"now"}}

**Comment by rashidkpc** [comment]
Changed title, looks like this applies to the query bar. Will dig into a fix.

**Comment by rashidkpc** [comment]
Fixed and released: https://github.com/elastic/timelion/commit/bfc3e90a63556982537e495a372b94e442f0d46e

Reinstall to get the fix.

**Comment by WarriorOfWire** [comment]
Confirmed resolved.  Thanks for your time Rashid, this is a major win!

**Comment by rashidkpc** [comment]
no problem, thanks for testing and letting me know :-)
