### ISSUE TITLE
Command/function to force time interval

### ISSUE THREAD

**Issue by calexicoz** [elastic/timelion#126]
I don't think it's already possible with Kibana and/or Timelion, but I'd like to look at timeseries with different intervals on the same page/dashboard. Typical example would be to be able to look at a metric over past week, past month, past year, all on the same page. So maybe something along the lines of `.period("-30d:now")`.

Right now it seems we're stuck with whatever the setting is in the upper right.

**Comment by rashidkpc** [comment]
Sorry, but this one isn't going to happen. Everything Timelion does depends on every chart being consistent, all having the same number of points, all in the same buckets. 

If you didn't care about the X-axis being accurate you could theoretically implement this on the dataSource layer by creating a dataSource argument that could query other ranges and then compress or expand the points along the x-axis as needed. In this case you'd simply be keeping the shape, not the actual data.

**Comment by calexicoz** [comment]
Right, I understand the requirements of all series in a particular chart using the same timeframe. That totally makes sense. But it would be nice in Kibana in general to be able to "set" a specific time period for a particular chart. It *is* helpful to be able to look at different timeframes at the same time to see the big picture.

So in my particular use case, all series would use the same period. There would not be any discrepancy. I just want to look at the same data for last 24h, week, month and year. And see it all in 1 dashboard.
