### ISSUE TITLE
Timelion sheet embedding

### ISSUE THREAD

**Issue by lmangani** [elastic/timelion#13]
Just like on the kibana dashboard, an option to embed bare timelion sheets and charts would be great to have.

**Comment by kodemaniak** [comment]
+1 That would be awesome.

**Comment by l8liu** [comment]
+1

**Comment by yehosef** [comment]
+1

**Comment by carlosvega** [comment]
+10000 ! 
Yes please, this would be great.

**Comment by carlosvega** [comment]
What is the priority of this issue? Should we expect this feature to be available soon?
Thanks and good work !

**Comment by carlosvega** [comment]
This is been closed but the feature is not available yet, why is it closed then? Thanks.
