### ISSUE TITLE
different index in kibana

### ISSUE THREAD

**Issue by carioka88** [elastic/timelion#132]
Hello, 
I have installed the timelion plugin, and I am having some issues.
In my kibana configuration, I have changed the kibana index:
    kibana.index: .kibana_mine
And I getting this error:

`node-kibana kibana: {"type":"response","@timestamp":"2016-05-27T14:54:02+00:00","tags":[],"pid":8385,"method":"put","statusCode":400,"req":{"url":"/elasticsearch/.kibana_mine/_mapping/timelion-sheet","method":"put","headers":{"host":"node-kibana.cern.ch:5602","connection":"keep-alive","content-length":"459","accept":"application/json, text/plain, */*","origin":"http://node-kibana.cern.ch:5602","kbn-version":"4.4.1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36","content-type":"application/json;charset=UTF-8","referer":"http://node-kibana.cern.ch:5602/app/timelion","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8,en-GB;q=0.6","cookie":"__utma=203412483.770705773.1452177822.1463646171.1463730414.15; __utmz=203412483.1463730414.15.7.utmcsr=jobs.web.cern.ch|utmccn=(referral)|utmcmd=referral|utmcct=/join-us/doctoral-student-programme; _ga=GA1.2.770705773.1452177822"},"remoteAddress":"128.141.193.102","userAgent":"128.141.193.102","referer":"http://node-kibana.cern.ch:5602/app/timelion"},"res":{"statusCode":400,"responseTime":45,"contentLength":9},"message":"PUT /elasticsearch/.kibana_mine/_mapping/timelion-sheet 400 45ms - 9.0B"}`

When I try to access to timelion in kibana, I only see a white page.
If I change the index, to the default one, then it show the timelion dashboard.
But it does not work for my case, where I have different kibana indexes...

Is it possible to change something in the timelion configuration?
Am I missing something?

Thanks in advance!

**Comment by rashidkpc** [comment]
Not sure what the issue is, try it with Kibana 4.5?

**Comment by rashidkpc** [comment]
Closing due to lack of feedback
