### ISSUE TITLE
split

### ISSUE THREAD

**Issue by khemtz** [elastic/timelion#133]
do you know fi i use a metric like sum, how show the top 5 of this sum using split function?

for example:

`.es(index='geolab*',split='rbs_sa:5',q='*',metric='sum:byt')`

> where:

> byt: number on byte format
> rbs_sa: string with the clients name

but when i see the top 5 i see the top 5 of a count, i mean this split only works like the metric was a count function

**Comment by rashidkpc** [comment]
This is intentionally not supported as the elasticsearch team is planning to remove this functionality from elasticsearch: https://github.com/elastic/elasticsearch/issues/17588
