### ISSUE TITLE
Can I use filter instead of query on Timelion .es()?

### ISSUE THREAD

**Issue by eadauto** [elastic/timelion#136]
I was wondering if there is any way to use filter instead of query on the timelion, when I use the and on the query instead of been more specific the number of results gets increases.

Thanks

Eric

**Comment by rashidkpc** [comment]
Elasticsearch filters are not supported, only lucene queries. I don't intend to support the Es DSL as it is implemented in json and exceedingly hard to read and write. 

I may at some point introduce a timelion specific query language.
