### ISSUE TITLE
y axis looks broken in 5.0.0-alpha3

### ISSUE THREAD

**Issue by dadoonet** [elastic/timelion#137]
Hey

I have 2 time series I'm printing using `.es(index="soundbeat-*",metric="min:right").bars(1),.es(index="soundbeat-*",metric="min:left").bars(1).multiply(-1)`.

With Kibana4, it was looking like this:

<img src="http://david.pilato.fr/blog/images/beats1/kibana5.png">

With Kibana5, I'm getting this:

<img width="1674" alt="timelion - kibana google chrome aujourd hui at 12 21 02" src="https://cloud.githubusercontent.com/assets/274222/15819194/04210eb8-2be2-11e6-8326-cc61e9eff029.png">

Which looks strange to me because when I print each time series on its own widget, I'm getting:

<img width="1671" alt="timelion - kibana google chrome aujourd hui at 12 21 48" src="https://cloud.githubusercontent.com/assets/274222/15819232/439cb466-2be2-11e6-9d69-3a3472057f7e.png">

Which looks good to me.

**Comment by dadoonet** [comment]
Note that if I don't multiply by `-1`, the graphics overlap and look good. So the Y Axis is correct in that case.

<img width="1670" alt="timelion - kibana google chrome aujourd hui at 12 32 17" src="https://cloud.githubusercontent.com/assets/274222/15819320/cf7da526-2be2-11e6-9e95-a0dc8ee43046.png">

**Comment by rashidkpc** [comment]
Don't have the code in front of me, but I think bars specifically are stacked by default now. Do .bars(stack=false)

**Comment by dadoonet** [comment]
@rashidkpc Indeed. Using `.es(index="soundbeat-*",metric="min:right").bars(width=1,stack=false),.es(index="soundbeat-*",metric="min:left").bars(width=1,stack=false).multiply(-1)` fixed it. Thanks!
