### ISSUE TITLE
Problem with precision in avg metric

### ISSUE THREAD

**Issue by dribault** [elastic/timelion#139]
Hello, 

I face an issue using a precision in timelion. I have some data which are in this format 106.834 with 3 decimals (see screenshot 1)
When I use this command it always round my output to the integer so it goes from 109 to 106
.es(index=alpha3mds,  metric='avg:OfferBestPrice', timefield='TimeStamp').precision(6)
So the precision is not taken into account (see second screenshot).

Do you see anything missing in my command?

![image](https://cloud.githubusercontent.com/assets/19858936/15967874/db670c02-2f29-11e6-8f15-c532ff7e338c.png)
![image](https://cloud.githubusercontent.com/assets/19858936/15967976/46d9beda-2f2a-11e6-9bfb-ae4386419406.png)

**Comment by rashidkpc** [comment]
What is your elasticsearch mapping? Perhaps these are being mapped to integers in elasticsearch? The precision function really just rounds stuff.

**Comment by dribault** [comment]
Hello

The data are pushed from the java api from float into numbers and the number format in kibana is set to 0.0(000) they are displayed with the right precision in other reports in kibana. 

Thanks

**Comment by rashidkpc** [comment]
Sure, but what is your elasticsearch mapping? Timelion doesn't use kibana's number formatting.

**Comment by dribault** [comment]
OK my bad i think you are rigt they are stored as long in this index. thanks
