### ISSUE TITLE
Weird problem with split bars fields in Kibana's graph after install timelion

### ISSUE THREAD

**Issue by Misakiri** [elastic/timelion#142]
Kibana verison: 4.5.1

Hi!
We have a lot of visualizations configured with Kibana that shows split bars fields as a separator.

Before install timelion, this separator appear in the graph with the name of the fields, but when we installed timelion, this legends only shows as "..." and not name at all.

Regards.

**Comment by rashidkpc** [comment]
Fixed here: https://github.com/elastic/timelion/commit/c36899500de28a3cff033f318fa7a60fff947f8e
