### ISSUE TITLE
Auto-select the best time scale

### ISSUE THREAD

**Issue by m82labs** [elastic/timelion#146]
Now that timelion graphs fit so nicely into a Kibana dash, it would also be nice if they would auto-scale the time interval, it could even be optional if we could use the 'interval' argument, and just set it to 'kibana'.

**Comment by rashidkpc** [comment]
Yeah, I really need to implement this, its really not hard either.

**Comment by rashidkpc** [comment]
Done and released: https://github.com/elastic/timelion/commit/44acf3de5ff02fe8d1c0ad2c15fb4250e73ac555

**Comment by m82labs** [comment]
Awesome, thanks for all the work on this project!
