### ISSUE TITLE
Plans for adding terms agg support?

### ISSUE THREAD

**Issue by joshuar** [elastic/timelion#15]
Are there any plans to add any bucket aggs support like terms agg?  I'd like to do something like: `.es(index='pingbeat-*',terms='target_host.raw',metric='avg:rtt')` i.e., calculate the average of the `rtt` field for the terms bucketed by the `target_host.raw` field?  It doesn't look like bucket aggs are supported (yet)?

**Comment by yehosef** [comment]
for the ordering, what about 
terms='field:target_host.raw size:10 order_by:count order:desc'

Filters aggs could be the same kind of structure
filters='<label>:"<filter>" "<filter_wo_label>"'
(maybe commas/semicolon would help here..)

I would start without multiple term aggs - this would handle many basic use cases without too much complexity (I think).

**Comment by nul** [comment]
+1

**Comment by rafaelzacarias** [comment]
+1

**Comment by frankkoornstra** [comment]
+1

**Comment by nul** [comment]
+1

**Comment by tomryanx** [comment]
+1, big time!

**Comment by nskalis** [comment]
+1

**Comment by c0deaddict** [comment]
+1

**Comment by mrjameshamilton** [comment]
+1

**Comment by nskalis** [comment]
+1

**Comment by rashidkpc** [comment]
Welp, given that Elasticsearch is discussing removing support for both sorting by ascending count and sorting by sub aggregations this just got *a lot* easier to implement

https://github.com/elastic/elasticsearch/issues/17614
https://github.com/elastic/elasticsearch/issues/17588

I also added the ability to pass arguments multiple times, so multi level terms aggs should be doable.

I'm not going to implement filters aggs as you can easily list off multiple .es() statements.

**Comment by rashidkpc** [comment]
terms agg support is in. Its the `split=field:count` argument to the .es() function

**Comment by nskalis** [comment]
thanks a lot @rashidkpc 
:) from which version of Kibana and on ?

**Comment by tomryanx** [comment]
@nskalis just uninstall the timelion plugin and reinstall
