### ISSUE TITLE
Auto-Refreshes breaks "movingaverage"

### ISSUE THREAD

**Issue by mike-marcacci** [elastic/timelion#153]
Timelion 5.0.0-alpha4 visualizations embedded in a kibana dashboard break when using an auto-refresh time.

For example, this visualization:

![image](https://cloud.githubusercontent.com/assets/690517/16788444/0725caec-485a-11e6-919c-2c9656611348.png)

gets re-rendered without its `movingaverage()` timelion expression applied:

![image](https://cloud.githubusercontent.com/assets/690517/16788448/0dc76ca2-485a-11e6-99ff-3ebf319483a3.png)

**Comment by mike-marcacci** [comment]
This is also true for manually pressing the "magnifying glass" search button.

**Comment by rashidkpc** [comment]
I'm unable to replicate this behavior, I think there's something else going on. Update timelion and see if it still happens?

![refresh](https://cloud.githubusercontent.com/assets/1250387/16890209/58b8e1ac-4aa1-11e6-8e0e-93f16887ad94.gif)

**Comment by rashidkpc** [comment]
Closing due to lack of feedback

**Comment by mike-marcacci** [comment]
Hi @rashidkpc - sorry for not replying earlier (your comment must have been buried in a pile of nagios alerts of some other distraction).

The only other potentially-relevant detail is that the visualization includes a "custom" interval of 15m vs the default of "auto." I'll try updating shortly, although I was on the latest as of 14 days ago.

Let me know if there's any additional information that might be useful!
