### ISSUE TITLE
TypeError: Cannot read property 'timeFieldName' of undefined

### ISSUE THREAD

**Issue by Prazzy** [elastic/timelion#155]
I have an app plugin "GCS4GQOS" and I am seeing below error after adding timelion chart to dashboard via "app/GCS4GQOS". However it works fine with "app/kibana" url.
```
GCS4GQOS.bundle.js?v=9889:39619 TypeError: Cannot read property 'timeFieldName' of undefined
    at Timefilter.get (GCS4GQOS.bundle.js?v=9889:134283)
    at GCS4GQOS.bundle.js?v=9889:143662
    at SearchSourceFactory.SearchSource._mergeProp (GCS4GQOS.bundle.js?v=9889:142984)
    at ittr (GCS4GQOS.bundle.js?v=9889:141680)
    at GCS4GQOS.bundle.js?v=9889:7719
    at GCS4GQOS.bundle.js?v=9889:8517
    at baseForOwn (GCS4GQOS.bundle.js?v=9889:7490)
    at GCS4GQOS.bundle.js?v=9889:8487
    at baseMap (GCS4GQOS.bundle.js?v=9889:7718)
    at Function.map (GCS4GQOS.bundle.js?v=9889:12154)
```

> 
> Timefilter.prototype.get = function (indexPattern) {
> 	      var filter;
> 	      **_var timefield = indexPattern.timeFieldName && _.find(indexPattern.fields, { name: indexPattern.timeFieldName });_**

Any help would be appreciated.

**Comment by rashidkpc** [comment]
This doesn't appear to be related to timelion. Timelion doesn't use `indexPattern` or `timeFieldName`. I'm not sure what `GCS4GQOS` is, but you might file a bug with the author of that plugin.
