### ISSUE TITLE
Can't seem to specify a different index

### ISSUE THREAD

**Issue by techwiz24** [elastic/timelion#156]
* Timelion v0.1.376
* Kibana v4.5.3
* Elasticsearch v2.3.3

Timelion appears to only be querying against `logstash-*` indices. In my system, I have a few different indices for different applications. For example, I'm exporting vSphere Performance metrics to an index that has the following pattern: `vsphere-yyy-MM-dd`. I've tried changing the `index` parameter (`.es(index="vsphere*")`) and the `default_index` option in `.../kibana/installedPlugins/timelion/timelion.js` and both return zero documents, however I can verify that I do have documents in these indices as I can view them in Kibana's `Discover` tab.

Furthermore, it appears that the `default_index: _all` setting is only returning documents from the logstash indices:

![image](https://cloud.githubusercontent.com/assets/794251/16962688/a6ee54a2-4dc0-11e6-8139-409076ea5069.png)

Is there a config setting I missed, or something I have to do to my indices to get timelion to recognize them?

**Comment by rashidkpc** [comment]
Pointing at the wrong es? Is it possible that your vsphere indices are using a different timefield? If you change `timelion.json` you may need to `rm -rf optimize/bundles` in your Kibana directory. I'm not able to replicate this behavior:

<img width="637" alt="screen shot 2016-07-19 at 1 40 11 pm" src="https://cloud.githubusercontent.com/assets/1250387/16965791/a4b7f6a2-4db6-11e6-8bcc-9c00a6cef678.png">

**Comment by techwiz24** [comment]
Ah, I think it was the timestamp field. I thought that was handled in the index mapping, but it must be a kibana thing. Changing the timestamp field in the `.es()` query now pulls results. Thanks!

**Comment by rashidkpc** [comment]
Cool, glad you sorted it out. I try to keep my timefield the same in all of my indices, if possible.
