### ISSUE TITLE
Installation issue on kibana 5.0

### ISSUE THREAD

**Issue by gspkibana** [elastic/timelion#160]
I am getting following error with timelion installation on Ubuntu 16.04:

./bin/kibana-plugin install timelion
Attempting to transfer from timelion
Attempting to transfer from https://download.elastic.co/kibana/timelion/timelion-5.0.0-alpha4.zip
Transferring 5349828 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in ./installedPlugins/timelion/public/services/saved_sheets.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /root/kibana/src/plugins/kibana/public/management/saved_object_registry in /root/kibana/installedPlugins/timelion/public/services
     @ ./installedPlugins/timelion/public/services/saved_sheets.js 11:2-60

===
Deleted file optimize/bundles/timelion.entry.js and tried again; same error

**Comment by rashidkpc** [comment]
I'm not seeing this issue, redownload kibana and try again? Also, try alpha5.

```
$ ./bin/kibana-plugin install timelion
Attempting to transfer from timelion
Attempting to transfer from https://download.elastic.co/kibana/timelion/timelion-5.0.0-alpha4.zip
Transferring 5368784 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
```

**Comment by rashidkpc** [comment]
Closing due to lack of feedback
