### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ishayw** [elastic/timelion#162]
we are receiving this error every time we try to access timelion using chrome:
Error: Uncaught TypeError: Cannot read property 'length' of undefined 

when we try to access it thru firefox we get the following:
Error: TypeError: format is undefined
we are using kibana 4.5.1 build 9892

**Comment by rashidkpc** [comment]
Try uninstalling and reinstalling timelion. Do you have the same issue with Kibana 4.5.4?

**Comment by ishayw** [comment]
We tried reinstalling, it didn't solve the problem.
We haven't tried it with kibana 4.5.4 yet, do you think this will solve the
problem?

**Comment by rashidkpc** [comment]
Possible, give it a shot, I don't test on older version of Kibana

**Comment by ishayw** [comment]
Just tried it, unfortunately the same error comes on, and that's after we
completely removed timeline and reinstalled it

**Comment by rashidkpc** [comment]
I'm puzzled on this one, I can't reproduce it

**Comment by rashidkpc** [comment]
This was probably related to the bad latest that got uploaded somehow, should be fixed now
