### ISSUE TITLE
Derivative on collectd not working

### ISSUE THREAD

**Issue by oazabir** [elastic/timelion#165]
I am trying to plot collectd CPU metrics on timelion. When I try to use the derivate, I see blank:

```
.es(index='collectd-*', q='collectd_plugin:cpu AND collectd_type_instance:user AND collectd_plugin_instance:0', metric='max:collectd_value').derivative()
```

![image](https://cloud.githubusercontent.com/assets/1611494/17650055/4cd454aa-623b-11e6-8415-91afd5506284.png)

But if I remove the derivate, I can see the data is there

```
.es(index='collectd-*', q='collectd_plugin:cpu AND collectd_type_instance:user AND collectd_plugin_instance:0', metric='max:collectd_value').bars().label("CPU")
```
![image](https://cloud.githubusercontent.com/assets/1611494/17650054/381fea4c-623b-11e6-8832-60cc87335452.png)

**Comment by rashidkpc** [comment]
I could be wrong here, but it looks like the value doesn't change at all? The derivative of a static series is 0.

**Comment by rashidkpc** [comment]
I'm going to guess its because of this `metric='max:collectd_value'` so you're asking for the highest value in every bucket, which, in your data, is always the same.

**Comment by oazabir** [comment]
The values are changing. It is collectd providing CPU metrics and it gives a cumulative value.

![image](https://cloud.githubusercontent.com/assets/1611494/17689517/3accd2e6-6380-11e6-97ed-d797e9e924f1.png)

**Comment by rashidkpc** [comment]
The values of the *documents* are changing, but I bet the value of `metric='max:collectd_value'` isn't, try with something like metric="avg:collectd_value".

**Comment by rashidkpc** [comment]
Closing for lack of feedback

**Comment by oazabir** [comment]
Sorry for not getting back sooner. The bar chart shows the output from max and avg and I can hover on the bars and see the values are certainly changing. But when I add the derivative function, it disappears.

**Comment by staaleo** [comment]
I have the same issue trying to use Timelion to graph interface traffic. using .points() i can see the values are increasing, but if i add derivative() the graph goes blank.
