### ISSUE TITLE
installing plugin creates an additional .chart-title section in kibana.style.css (breaks graph labels)

### ISSUE THREAD

**Issue by kmike82** [elastic/timelion#166]
Installing timelion creates two '.chart-title' sections in kibana.style.css. The settings required by timelion break the x/y axis labeling for non timelion charts with multiple sub aggregations (example: line chart with split charts on term)

I am getting around this by changing the one that timelion needs from:
.chart-title { ... }
to:
.timelion-vis .chart-title { ... }

**Comment by rashidkpc** [comment]
This was fixed awhile ago: https://github.com/elastic/timelion/commit/7c750dbab78b522144eb6b44e2dcdfc7ca27b59b

Uninstall and reinstall timelion and you should be good.
