### ISSUE TITLE
Broken with Kibana 4.5.4?

### ISSUE THREAD

**Issue by blavoie** [elastic/timelion#168]
Since we upgraded to 4.5.4, Timelion is showing a blank page.
Tried with Firefox and Chrome.

Am I dreaming? Can you reproduce?

I've tried to reinstall multiple times from fresh Kibana without any success.

Thanks

**Comment by rashidkpc** [comment]
Fixed, somehow 0.1.168 got published as latest. No idea. Anyway, republished 0.1.402 and everything looks fine. https://github.com/elastic/timelion/issues/172
