### ISSUE TITLE
Timefield required

### ISSUE THREAD

**Issue by matthughes** [elastic/timelion#169]
I have four time-based indicies.  Three of them work fine with Timelion using queries such as:

`es(index='myindex-*')`

However, my fourth index never plots anything.  The data shows up in the same time period in regular Kibana queries.  I've double-checked the spelling a million times.  No errors show up in either JS console or Kibana backend logs.  Inspecting the network return from `run`, I see that indeed, Timelion thinks the count should be 0.  The three indices that work have `@timestamp` as a time field.  The one that doesn't work uses `start-time`.  

The query works if I set `timefield` manually in the expression.  Couple questions:

1) Shouldn't Timelion be able to grab the timefield from Kibana index?
2) What is happening when I don't specify `timefield`?  The index in question only has one field with date type.  Shouldn't Timelion default to that field?
3) If Timelion can't find the field, shouldn't it error out instead of returning 0 results?

**Comment by rashidkpc** [comment]
1) Sure
2) Sure
3) This is a behavior of elasticsearch 

I opened https://github.com/elastic/timelion/issues/171
