### ISSUE TITLE
Empty split series showing up in legend

### ISSUE THREAD

**Issue by jfshiuan** [elastic/timelion#175]
Say I create a series with data from an Elasticsearch index, and I split it on some field, and take the average of another field. So something like .es(index=indexName, metric=avg:MyNumField, split=SplitField:10). For some of the SplitField values, there are no associated MyNumField values within the given time frame, so nothing shows up on the chart for that SplitField value. However, that SplitField value still shows up in the legend, even though it has no data in the chart.

It would be nice if we could filter these empty labels out of the legend.

**Comment by rashidkpc** [comment]
```
.es(q="_exists_:MyNumField", index=indexName, metric=avg:MyNumField, split=SplitField:10)
```

That should solve your probably by only pulling back results in which `MyNumField` exists
