### ISSUE TITLE
overloading sources and functions

### ISSUE THREAD

**Issue by ddavidebor** [elastic/timelion#178]
can datasources and chainables (such as `.divide()`) be overloaded like in this silly example?

example:

The hypothetical chainable/datasource hybrid "addFromZero(x)" behave as follows:

* if datasource, return x
* if chainable, add x

```
.value(1).addFromZero(123) will add 123 to value, plotting 124
.addFromZero(123) will plot 123
```

can this be easily done or is it a mess?

Davide

**Comment by ddavidebor** [comment]
Now apparently if a datasource and a chainable have the same term one will overwrite the other.

Regarding #174 we have created a datasource called `.maths()` and a chainable called `math()` but it's not the cleanest implementation.

**Comment by rashidkpc** [comment]
No, you can not overload in this manner, and I'd prefer not, for simplicity's sake. You could always start a chain with .static(0)

**Comment by ddavidebor** [comment]
Thy will be done
