### ISSUE TITLE
Timelion plots identifier

### ISSUE THREAD

**Issue by SimoneTosato** [elastic/timelion#179]
For [our project](https://github.com/fermiumlabs/mathlion) me and my colleague need to instance separate variable scope for each plot and to do that it would be useful to have something to identify each plot. Is there any way to do that in timelion?

**Comment by rashidkpc** [comment]
Can you elaborate? I don't really understand what you're looking for here?

**Comment by ddavidebor** [comment]
Translating from @SimoneTosato: 

We need a way to share an object in memory in a way that all the chains (.datasource.chainable...) in a single plot can use it together, but the object should be unique to each and every plot.

Now we're simply saving the object [here](https://github.com/fermiumlabs/mathlion/blob/master/functions/math-enviroment.js#L3) but it's common to every timelion plot (even those in the dashboards).

It's the environment in which to save the math.js variables. It needs to be written-by and read-by different functions: some of them *datasource*  and some of them *chainable. 

A simple way could be to have a unique identifier (UUID) that identifies every plot, this way we could easily separate the variables.

Davide

**Comment by rashidkpc** [comment]
A UUID could work. You could probably also probably use the index of the plot in the array.

**Comment by ddavidebor** [comment]
@rashidkpc is that index always unique between both the timelion app and the dashboards panels in the main kibana app?

**Comment by rashidkpc** [comment]
On the kibana dashboard there will only ever be 1 plot per request.

**Comment by rashidkpc** [comment]
Going to close this since I think we have our solution
