### ISSUE TITLE
Install error / wrong github URL

### ISSUE THREAD

**Issue by TiNico22** [elastic/timelion#18]
With K4.2.1 under windows with the ".\bin\kibana plugin -i kibana/timelion" command, the download from elastic.co failed on my network, but the fallback to github seems to go to the wrong URL :  https://github.com/kibana/timelion/archive/master.tar.gz instead of https://github.com/elastic/timelion/archive/master.tar.gz ?

Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\UserA\ELKbin\Kibana\kibana-4.2.1-windows>.\bin\kibana plugin -i kibana/timelion
Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).
Installing timelion
Attempting to extract from https://download.elastic.co/kibana/timelion/timelion-latest.tar.gz
Error: getaddrinfo ENOTFOUND download.elastic.co
Attempting to extract from https://github.com/kibana/timelion/archive/master.tar.gz
Error: getaddrinfo ENOTFOUND github.com
Plugin installation was unsuccessful due to error "Not a valid url."

**Comment by rashidkpc** [comment]
It isn't installable from github, if you can't resolve download.elastic.co you won't be able to install it.
