### ISSUE TITLE
X-axis Timeline is not rendered correctly in Timelion Graph

### ISSUE THREAD

**Issue by skirankumars31** [elastic/timelion#180]
The timeline of the events are wrong in Timelion when i view it by month. When i view it by week it appears it appears close but not correct

This is what i see when i see it by week. As you can see the events start in first week of July but it actually starts from 17th of July

![image](https://cloud.githubusercontent.com/assets/1437258/18253165/c84eaad2-7392-11e6-8588-85c8c732dfc9.png)

This is what i see when i see it by month. This shows the events start from June but the first event is from 17th July

![image](https://cloud.githubusercontent.com/assets/1437258/18253206/1ffb7666-7393-11e6-9156-57fcb9d78ab0.png)

This is what i see in Kibana discover when i see the events.I have set the Execution_Date as my timefield in timelion.json

![image](https://cloud.githubusercontent.com/assets/1437258/18253234/5f991850-7393-11e6-9f99-e69449beeaa5.png)

**Comment by rashidkpc** [comment]
Your Kibana chart seems to be last 60 days at a daily interval. This would not encompass June, nor the start of July. You timelion chart is set to monthly or weekly, and for the last 6 months. Can you take a screenshot of Kibana with a monthly and weekly interval and a timespan of the last 6 months? 

Also, the elasticsearch queries that are being sent would be helpful.

**Comment by rashidkpc** [comment]
Closing due to lack of feedback
