### ISSUE TITLE
Fill gaps when no data is available on timeseries

### ISSUE THREAD

**Issue by toshiro92** [elastic/timelion#182]
Hi !

I have an issue about timeseries on Timelion, I currently have a timeserie like this below:

![gaps_timelion](https://cloud.githubusercontent.com/assets/17139715/18360264/9559d76a-75fd-11e6-83ef-1bea52dac541.png)

However I wanted to fill gaps between those data, like Kibana already do (even if this is not as readable as in timelion):

![no_gaps_kibna](https://cloud.githubusercontent.com/assets/17139715/18360274/a26fdbc0-75fd-11e6-8411-d2b69d00da4c.png)

I know that an if statement like **_.if(eq, null, 0)_** could be a solution, however I want a continuity between the previous and next data (like Kibana's do). On [ElasticSearch](https://discuss.elastic.co/t/timelion-how-to-fill-gaps-when-no-data-is-available-on-timeseries/59753) forum, it seems to be an inexistent feature, which could be useful.

**Comment by rashidkpc** [comment]
You can do this with the `.fit()` function

![screen shot 2016-09-09 at 12 03 36 pm](https://cloud.githubusercontent.com/assets/1250387/18399382/7fdddb38-7685-11e6-94df-f718c989c435.png)

**Comment by toshiro92** [comment]
Thanks for the info ! I updated my post on ES too
