### ISSUE TITLE
Add "hide zero results" in .points()

### ISSUE THREAD

**Issue by Crazyigor1987** [elastic/timelion#185]
Sometimes you need to hide Zeros within the timeline. Useful for error monitoring. Otherwise we have such weird visualisation:

![bug error events](https://cloud.githubusercontent.com/assets/16761737/18515187/c690a7fa-7a94-11e6-8c74-a2228724ce56.png)

**Comment by rashidkpc** [comment]
You can already do this by setting zero to null:

`.if(eq, 0, null)`
