### ISSUE TITLE
Cardinality + query fails

### ISSUE THREAD

**Issue by olivierlambert** [elastic/timelion#186]
Hi lads,

Using latest kibana (5RC1) with latest ES (5 RC1 too).

When using Kibana to display a metric with a unique count, I got the "right" result (in my case, 19 hits). It creates this request behind:

``` json
{
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "operation:plan.cancel",
            "analyze_wildcard": true
          }
        },
        {
          "range": {
            "date": {
              "gte": 1413122277504,
              "lte": 1476280677504,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "must_not": []
    }
  },
  "aggs": {
    "1": {
      "cardinality": {
        "field": "customerEmail"
      }
    }
  }
}
```

Using the same principle on TL isn't working (21 hits).

My request: `.es(q='operation:plan.cancel', metric='cardinality:customerEmail').cusum()` returns a graph with the latest number at 21. If I remove the cardinality, I got the **exact** same result.

Maybe my query isn't correct?

**Comment by rashidkpc** [comment]
Please file this over at https://github.com/elastic/kibana, we're winding down this repo now that timelion has been merged into Kibana

**Comment by olivierlambert** [comment]
Will do, thanks!
