### ISSUE TITLE
Negative values do not display when setting yaxis()

### ISSUE THREAD

**Issue by markjandejong** [elastic/timelion#188]
I have a chart that includes two series. One of them only includes negative values. The chart displays fine when yaxis is not set, but when it is set with all defaults (yaxis()), all negative values disappear. When both series are set to only display negatives, the chart remains completely blank. 

The workaround, though not preferable, is the set a yaxis minimum value (min=-<num>) which brings the negative values back into view. 

Any suggestions? Let me know if you need any further details.

**Comment by tbragin** [comment]
@dejongm Timelion is now part of Kibana. Could you file this issue in https://github.com/elastic/kibana/issues when you get a chance?

**Comment by tbragin** [comment]
It appears this issue has already been filed in the kibana repo: https://github.com/elastic/kibana/issues/9040
