### ISSUE TITLE
Kibana 5.0.1 x-pack plugin installation failure

### ISSUE THREAD

**Issue by kvopencode** [elastic/timelion#190]
What is the problem here. X-pack plugin not getting installed in kibana

F:\PerformanceAnalyzer\kibana501\bin>**kibana-plugin install x-pack**
Attempting to transfer from x-pack
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugin
s/x-pack/x-pack-5.0.1.zip
Transferring 56957357 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
**Plugin installation was unsuccessful due to error "Optimizations failure.**

    ERROR in ../plugins/x-pack/plugins/graph/public/app.js
    Module not found: Error: Cannot resolve module 'ace' in F:\PerformanceAnalyz
er\kibana501\plugins\x-pack\plugins\graph\public
     @ ../plugins/x-pack/plugins/graph/public/app.js 13:0-14

    ERROR in ../src/ui/public/tooltip/tooltip.js
    Module not found: Error: Cannot resolve module 'ui-bootstrap' in F:\Performa
nceAnalyzer\kibana501\src\ui\public\tooltip
     @ ../src/ui/public/tooltip/tooltip.js 9:0-23

    ERROR in ../src/core_plugins/kbn_doc_views/public/views/json.js
    Module not found: Error: Cannot resolve module 'ace' in F:\PerformanceAnalyz
er\kibana501\src\core_plugins\kbn_doc_views\public\views
     @ ../src/core_plugins/kbn_doc_views/public/views/json.js 13:0-14

    ERROR in ../src/core_plugins/kibana/public/dashboard/directives/grid.js
    Module not found: Error: Cannot resolve module 'gridster' in F:\PerformanceA
nalyzer\kibana501\src\core_plugins\kibana\public\dashboard\directives
     @ ../src/core_plugins/kibana/public/dashboard/directives/grid.js 17:0-19

    ERROR in ../src/core_plugins/kibana/public/management/sections/objects/index
.js
    Module not found: Error: Cannot resolve module 'ace' in F:\PerformanceAnalyz
er\kibana501\src\core_plugins\kibana\public\management\sections\objects
     @ ../src/core_plugins/kibana/public/management/sections/objects/index.js 13
:0-14
"

**Comment by rashidkpc** [comment]
timelion is not part of X-pack, please file this issue in the upstream elastic/kibana repo.
