### ISSUE TITLE
Quandl (external resources) outgoing proxy connection

### ISSUE THREAD

**Issue by v01t** [elastic/timelion#191]
Timelion (kibana 5) located inside of corporate network, access to external (internet) end-points like quandl api are possible only by specifying outgoing proxy, is there possibility to define it (or hard-code somewhere)?
Thanks.

**Comment by tbragin** [comment]
@v01t Timelion is now part of Kibana. Could you file this issue in https://github.com/elastic/kibana/issues when you get a chance?
