### ISSUE TITLE
Timelion "munging" Timestamps

### ISSUE THREAD

**Issue by packet-rat** [elastic/timelion#192]
Timelion functions do not work.  When running through the startup helper noted that the range of dates are completely off. 

**January 2, 0201 7:00 PM and August 2, 2103 8:00 PM.** 

 All Timestamp fields look good in Documents and are recognized as Dates.

```Good news Elasticsearch is configured correctly!

Or at least, things look ok. I validated your default index and your timefield and everything looks ok. 
Given your settings I found data between January 2, 0201 7:00 PM and August 2, 2103 8:00 PM.
You're probably all set. ```

**Comment by tbragin** [comment]
@packet-rat Timelion is now part of Kibana. Could you file this issue in https://github.com/elastic/kibana/issues when you get a chance?

**Comment by packet-rat** [comment]
FYI I think the problem was with mis-translated epoch times.
