### ISSUE TITLE
Bars lack accuracy when wide

### ISSUE THREAD

**Issue by darkmooink** [elastic/timelion#193]
I have been using bars and realized that when I make them wide they grow in width in all directions, this means that a wide bars grow in height and thus make them less accurate. Is there a way of making the bar width change how wide the bars are in the horizontal without changing the vertical width?

How to replicate: use the expression `.value(1).bars(15).color(red) .value(1).color(green)` and you will see that the red is above the green line when they should be at the same level.

**Comment by tbragin** [comment]
@darkmooink Timelion is now part of Kibana. Could you file this issue in https://github.com/elastic/kibana/issues when you get a chance?
