### ISSUE TITLE
Search ignores time interval. 

### ISSUE THREAD

**Issue by splokhikh** [elastic/timelion#195]
I have many indices and when I try evaluate any expresion in Timelion, I getting error:

> Timelion: Error:  in cell #1: [illegal_argument_exception] Trying to query 1050 shards, which is over the limit of 1000. This limit exists because querying many shards at the same time can make the job of the coordinating node very CPU and/or memory intensive. It is usually a better idea to have a smaller number of larger shards. Update [action.search.shard_count.limit] to a greater value if you really want to query that many shards at the same time.
![_016](https://cloud.githubusercontent.com/assets/8625900/21614387/56496574-d1ea-11e6-890e-f46197497112.png)
Timelion ignores required time period.

**Comment by tbragin** [comment]
@plokhikh Timelion is now part of Kibana. Could you file this issue in https://github.com/elastic/kibana/issues ?

**Comment by pjcard** [comment]
Hi @tbragin, I've also noticed this issue after being surprised at receiving the same error under the same circumstances, and so I've added a bug in the location you've suggested. Thanks.
