### ISSUE TITLE
Labeled Y axis show black text on dark theme

### ISSUE THREAD

**Issue by loekvangool** [elastic/timelion#196]
On a dark theme, the Y-axis labels show up as black making them hard to read.

Left is default, right is a custom color with `yaxis(color=#ccc)`
<img width="807" alt="screen shot 2017-02-05 at 18 09 13" src="https://cloud.githubusercontent.com/assets/7300472/22628108/91fee938-ebce-11e6-871b-483a089c6b3b.png">

On a dark theme dashboard, black stays black, while other components do change to light gray:
<img width="73" alt="screen shot 2017-02-05 at 18 09 34" src="https://cloud.githubusercontent.com/assets/7300472/22628109/94c38a52-ebce-11e6-84eb-d5f7cbc9f5a1.png">

**Comment by tbragin** [comment]
@loekvangool  Timelion is now part of Kibana. Could you file this issue in https://github.com/elastic/kibana/issues ?
