### ISSUE TITLE
Odd looking stacked bars

### ISSUE THREAD

**Issue by kimyx** [elastic/timelion#199]
Using bars in timelion like this:

```
.es(index="mms-overwritten", metric="max:catZero", timefield="date").bars(stack="true", width=50).label("Category Zero").color(  #1e52eb ),  
.es(index="mms-overwritten", metric="max:catOne", timefield="date").bars(stack="true", width=20).label("Category One").color(#f66),  
.es(index="mms-overwritten", metric="max:catTwo", timefield="date").bars(stack="true", width=20).label("Category Two").color(#e1e73e),  
.es(index="mms-overwritten", metric="max:catThree", timefield="date").bars(stack="true", width=10).label("Category Three").color(#ae61fc),  
.es(index="mms-overwritten", metric="max:catFour", timefield="date").bars(stack="true", width=20).label("Category Four").color(#2fc2c4)
```
Normally all the widths are set to 10, but the varying widths makes a problem obvious that only shows up randomly otherwise.

With these widths, the chart looks as shown here:

![timelion_bars](https://cloud.githubusercontent.com/assets/8986361/23877428/eb100f0c-0807-11e7-940a-c9d1bf3ae284.png)

Setting the width to 50 on the "Category Four" set of bars makes it hang below the x-axis. Reducing the width to 10 makes it look ok. It's as if the bar must be at least as high as it is wide, and that can push it below the axis.

Also, this chart looks the same whether I set stack="true" or stack="false". I'd expect them to differ.

Using kibana 5.1.1 and the timelion that came with it.

**Comment by tbragin** [comment]
@kimyx  Timelion is now part of Kibana. Could you file this issue in https://github.com/elastic/kibana/issues ?
