### ISSUE TITLE
Don't recalculate queries if only something display related changed

### ISSUE THREAD

**Issue by yissachar** [elastic/timelion#200]
I'm running a pretty resource intensive Timelion query, so it takes a while to display. However, even when changing simple things like the label it seems to be recalculating the entire query, which it shouldn't need to do.

If I already ran:

`.es(q="something complicated", metric="foo").label("This is a thing")` 

Then changing it to:

`.es(q="something complicated", metric="foo").label("This is the same thing")` 

Should really just be a client-side change and not take forever to execute.

This doesn't only apply to `.label()` of course, `.color()`, `.title()` etc. have the same issue.

**Comment by tbragin** [comment]
@yissachar  Timelion is now part of Kibana. Could you file this issue in https://github.com/elastic/kibana/issues ?

**Comment by yissachar** [comment]
Not sure how I missed the big notice in the README, sorry. Issue filed here https://github.com/elastic/kibana/issues/10892
