### ISSUE TITLE
Kibana 5 issues with Timelion not working at all.

### ISSUE THREAD

**Issue by RPGambit2** [elastic/timelion#206]
I see that it is included within Kibana.   Is there any install commands that need to be done, 

i.e. ./bin/kibana plugin -i elastic/timelion???

I changed the configuration to use my timefield:

  "es": {
    "timefield": "StartTimeTimestamp",
    "default_index": "_all"
  },

however, I still get 0 records.   Is there something else I am supposed to be doing?   Kibana is working fine with my indexes.

Thanks!

**Comment by rashidkpc** [comment]
Please open issues on elastic/kibana
