### ISSUE TITLE
scale.interval draws incorrect graph

### ISSUE THREAD

**Issue by Sjaak01** [elastic/timelion#207]
Hi,

I'm having a problem with the scale.interval not drawing the graph I'm expecting.

I'm trying to make a bytes per second graph based on netflow data. However when I create a graph using timelion and set the interval to auto and scale.interval(1) timelion creates a big data spike when a lots of data comes in.

https://discuss.elastic.co/uploads/default/original/3X/8/a/8a37a3988ce0ce0c0885776cd19e6395572fe3e2.png

This screenshot is while downloading a large test file. My device sends netflow data every minute so the big spikes are the test download data coming in every minute.

The top screenshot uses the following code and creates the desired graph but is unusable for large time periods as it creates too many buckets.

`$q='vessel_name:Vessel_1', .es($q,metric='sum:netflow.out_bytes').divide(60).divide(1024)`

The bottom screenshot uses scale.interval and the following code.

`$q='vessel_name:Vessel_1', .es($q,metric='sum:netflow.out_bytes').scale_interval(1s)`

When I zoom out enough, lets say 4 hours or a day, then the graph looks okay but as soon as I zoom in I get the spiky graphs rather than a smooth line.

Is there any way make this work?

**Comment by rashidkpc** [comment]
Fair to say this was resolved: https://discuss.elastic.co/t/bytes-per-second-is-it-possible/83497/14
