### ISSUE TITLE
Could not validate elasticsearch config. Check timelion.json, restart Kibana, and try again

### ISSUE THREAD

**Issue by whilke** [elastic/timelion#23]
Just installed plugin and tried to run it. 

Looks like the config file is fine, and defaults to the _all index. I changed the index but still get the same result.

Also when running a search I get back:

Timelion: Error: in cell #1: es() returned no results

**Comment by rashidkpc** [comment]
Possibly incorrect timefield? Time range too narrow?

**Comment by whilke** [comment]
tried all time ranges, have over 200m docs in cluster. Kabana works off the timefield in the docs, so don't think it's incorrect.

**Comment by rashidkpc** [comment]
Kibana has the time field set per index pattern, timelion doesn't use patterns, there's a default timefield set in timelion.json

**Comment by rashidkpc** [comment]
Closing due to lack of feedback

**Comment by whilke** [comment]
Not sure why you just closed this out. But my index uses "timestamp" as the time field, which is the default in the config file.

Or why that has anything to do with this error:

Could not validate elasticsearch config. Check timelion.json, restart Kibana, and try again. (1)


I'll check back once this has matured a bit and see if the error handling reports something more descriptive that points at the problem.

**Comment by alecklandgraf** [comment]
@whilke 
FWIW, I had the same error, and inspecting the caught response from the timelion route `validate_es.js` AJAX response was empty. 

My issue, I think, was the default `timefield`being set to `@timestamp` instead of `timestamp` in my case. I'm not using logstash and my `sensor_log` index has the field `timestamp` without the `@`.

I then had to stop and restart kibana to get the new `timelion.json` to validate. Clicking the validate button showed the same error.

@rahsharpe maybe the UI button that says click to validate should include some help text to restart kibana. 

```json
"es": {
    "timefield": "timestamp",
    "default_index": "sensor_log",
    "allow_url_parameter": false
  }
```

**Comment by inqueue** [comment]
Received a report of this issue.

`/timelion/validate/es/` returns

```
 {
 	ok: false,
 	resp: {}
 }
```

No errors in the log. Here is the current config:

```
 	{
 		"quandl": {
 			"key": ""
 		},
 		"es": {
 			"timefield": "timestamp",
 			"default_index": "_all",
 			"allow_url_parameter": false
 		},
 		"graphite": {
 			"url": "https://www.hostedgraphite.com/UID/ACCESS_KEY/graphite"
 		},
 		"default_interval": "1h",
 		"max_buckets": 2000
 	}
```

**Comment by carlosvega** [comment]
Same here !

**Comment by LFischerstrom** [comment]
@carlosvega Which exact versions of Kibana and Timelion are you using? I just downgraded to Kibana 4.4.0 and I still get the same error.

**Comment by carlosvega** [comment]
I'm using Kibana 4.4.1 and I don't know the Timelion version, I think is the last one because I installed it using the plugin option of kibana. Hope it get fixed soon :/

**Comment by rmrfslashbin** [comment]
I've had the same issue; I can't technically say why the issue comes and goes; but, when I do see the above scenario, I restart kibana and the issue resolves. After some time (and I assume some event) the issue reappears.

**Comment by petabyte** [comment]
Same here having the same issue.

**Comment by alaniemieckota** [comment]
my config is like this: {
  "quandl": {
    "key": ""
  },
  "es": {
    "timefield": "timefield",
    "default_index": "logstash-*",
    "allow_url_parameter": false
  },
  "graphite": {
    "url": "https://www.hostedgraphite.com/UID/ACCESS_KEY/graphite"
  },
  "default_interval": "1h",
  "max_buckets": 2000
}

the issue was on "timefield"
my index has property named: timefield so i change it and removed @

**Comment by carlosvega** [comment]
Is it fixed on Kibana 4.4.2 ?

**Comment by mmalesevic** [comment]
No, just had to remove the @ in "timefield" value, but after this it works... 
So at least its not to hard to fix ;)

**Comment by rashidkpc** [comment]
This is fixed, there was some debug code that could cause issues included.
