### ISSUE TITLE
Make timelion as a visualization provider for Kibana

### ISSUE THREAD

**Issue by rcrezende** [elastic/timelion#29]
Would be nice to leverage existing Kibana dashboards with Timelion visualizations. 
If the concept of visualization is generalized and a data/schema interface is defined, multiple Kibana Apps could provide visualizations for the Dashboard solution.

**Comment by damianpfister** [comment]
+1

**Comment by sand0id** [comment]
+1, this would be very useful

**Comment by lukaszkregiel** [comment]
everything on one dashboard, yeaa +1

**Comment by rashidkpc** [comment]
I too would like todo this. The caveat would be that filters probably wouldn't be applied to timelion panels. Time selection and such would still work, but we'd need some sort of indication that other filters would not be applied

**Comment by yehosef** [comment]
In general I think it's valuable if kibana visualization have the option to listen to the outer filters/timeframe.  Often that's useful that everything is interconnected, but sometimes it's not desired.  Ideally I think it should be an option at the dashboard level when inserting the visualization.

If the timeline panels were just iframes, you could choose to include the filter and send it via window.postMessage, it seems.

But even without all this, I think it would be valuable to add them to the dashboards even before there is any kind of optional filters for visualizations.

**Comment by paulbarr** [comment]
This would be a great enhancement to have - is there any even rough idea of a timeline for when this enhancement might be targetted for?

**Comment by oryband** [comment]
@rounds/server

**Comment by pemontto** [comment]
:+1:

**Comment by cero-t** [comment]
+1

**Comment by kaib** [comment]
+1

**Comment by sai-rupanagudi** [comment]
+1

**Comment by lavaalone** [comment]
+1

**Comment by linux-devil** [comment]
+1

**Comment by oryband** [comment]
No need for +1ing issues anymore, please add a +1 reaction to OP

**Comment by rashidkpc** [comment]
This is done, uninstall and reinstall to get it.
