### ISSUE TITLE
How to delete a sheet?

### ISSUE THREAD

**Issue by l8liu** [elastic/timelion#30]
I couldn't find a place to delete a sheet. The only possible place is when I click 'open sheet' icon, there is a link called 'manage saved sheets' at the top right corner. However when I click it, it just give an almost blank window except 'timelion' logo line at the top. It will be very appreciate f you could look at this issue.

**Comment by rashidkpc** [comment]
There is currently no way todo this, we need to make the saved object editor pluggable in Kibana

**Comment by tbragin** [comment]
Timelion is now part of Kibana, so I filed this issue here: https://github.com/elastic/kibana/issues/9055
