### ISSUE TITLE
Option to float the input "query" text box

### ISSUE THREAD

**Issue by polyfractal** [elastic/timelion#32]
If the page becomes filled with charts, it's a pain to keep scrolling up to edit the chart's query.  The workflow ends up being:

1. Edit chart query
2. Click somewhere to refresh the charts (hitting enter does not always seem to work)
3. Wait for spinner to finish
4. Scroll down, inspect chart
5. Scroll up, make small change, goto step 2

If the text box floated at the top of the screen, it'd make manipulating long pages of charts a lot easier.

**Comment by rashidkpc** [comment]
Does that not currently happen?

![fixedquery](https://cloud.githubusercontent.com/assets/1250387/11602184/8e850750-9a95-11e5-959f-8a5d09473ed8.gif)

**Comment by polyfractal** [comment]
Sigh.  Memo to self: update local copies of plugins before filing tickets :)
