### ISSUE TITLE
Moving standard deviation

### ISSUE THREAD

**Issue by l8liu** [elastic/timelion#33]
Similar to the moving average function (.mvavg() or .movingaverage()), could Timelion provide a moving standard deviation function to compute the standard deviation at a given time window, so we can easily generate some control charts. 

Also I found the current Timelion has quite limited math functions. Could you please add some functions like square root?

**Comment by tomryanx** [comment]
This would be .movingstd() / .mvstd()

**Comment by rashidkpc** [comment]
Indeed this already implemented
