### ISSUE TITLE
Making bars stackable

### ISSUE THREAD

**Issue by cyril-steimer** [elastic/timelion#34]
Any plans to make it possible for bars to be displayed in stacked mode and side by side mode as well?

**Comment by rashidkpc** [comment]
Stackable, yes, side by side, probably not. Last I looked flot's side-by-side plugin wasn't perfect.

**Comment by tbragin** [comment]
+1

**Comment by aodj** [comment]
Is there perhaps the ability to offset the bars? That way you could assign a given pixel offset based upon the width of your bars.

**Comment by nul** [comment]
+1

**Comment by lavaalone** [comment]
+1

**Comment by rashidkpc** [comment]
Stacked bars now available: https://github.com/elastic/timelion/commit/37a66525b795f2c57fe69182b01a36bd1fc44984

I opened #111 for side-by-side
