### ISSUE TITLE
Installation Problem (Cannot resolve module 'pegjs')

### ISSUE THREAD

**Issue by CZuegner** [elastic/timelion#36]
/opt/kibana-4.3.0/bin/kibana plugin --install elastic/timelion
Installing timelion
Attempting to extract from https://download.elastic.co/elastic/timelion/timelion-latest.tar.gz
Attempting to extract from https://github.com/elastic/timelion/archive/master.tar.gz
Downloading unknown number of bytes
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in /opt/kibana-4.3.0/installedPlugins/.plugin.installing/public/directives/expression_directive.js
    Module not found: Error: Cannot resolve module 'pegjs' in /opt/kibana-4.3.0/installedPlugins/.plugin.installing/public/directives
     @ /opt/kibana-4.3.0/installedPlugins/.plugin.installing/public/directives/expression_directive.js 6:10-26
"

**Comment by rashidkpc** [comment]
Wrong command: `/opt/kibana-4.3.0/bin/kibana plugin --install kibana/timelion`
