### ISSUE TITLE
movingaverage shifts data to the right

### ISSUE THREAD

**Issue by derickson** [elastic/timelion#37]
the movingaverage() function does an average convolution filter _window wide.  The _window is defined with .slice( i - _window, i)  basically looking to the left on the timeline _window items.  as a result peaks and valleys in the smoothed data shift to the right.

A fix would be to have the convolution be center anchored rather than right anchored.

**Comment by derickson** [comment]
picture of phase shift introduced by current movingaverage() and fixed with modification

![image](https://cloud.githubusercontent.com/assets/945150/11708036/01f29ea0-9f5f-11e5-982a-843cd9e3d285.png)

**Comment by rashidkpc** [comment]
Yeah, definitely not nice

**Comment by derickson** [comment]
I figured out how to gulp into a kibana dev environment.  Feeling very proud of myself for that one.

I added the toggle logic but am having trouble wording the param, options and help in a way that would make sense to a user who doesn't know how the code or terminology for a convolution filter works.  Thoughts on that?  I went for a param named 'position' and 'Position of the averaged points relative to the result's time.  Options are left, right, and center (default).'

Added picture of what help looks like.

![movingaverage](https://cloud.githubusercontent.com/assets/945150/11765977/e12d9d90-a13f-11e5-95b7-f75e8691eec0.jpg)

**Comment by oryband** [comment]
@gadisr @liorama @avivl @doodyparizada

**Comment by rashidkpc** [comment]
Closed by pull from @derickson

**Comment by oryband** [comment]
@rashidkpc which issue/pr?
