### ISSUE TITLE
#document List of functions

### ISSUE THREAD

**Issue by ebuildy** [elastic/timelion#41]
Hello,

Sorry to post this as an issue, but where is the documentation with all the functions?

Thanks you,

**Comment by yehosef** [comment]
+1

**Comment by yangbaida** [comment]
+1

**Comment by bigl0af** [comment]
I'd like that PDF...

**Comment by yangbaida** [comment]
Here is the Document :)
Download Link：http://pan.baidu.com/s/1qXuWLDa 
Password：8vlc

**Comment by rashidkpc** [comment]
![screen shot 2016-01-22 at 1 34 34 pm](https://cloud.githubusercontent.com/assets/1250387/12522287/0cd15f44-c10d-11e5-8241-d4b08c5cb9e9.png)

This exists in the application, click the help icon. If you haven't been through the tutorial it, you should. The function reference is shown by default once you click "Don't show this again". There's also a link in the first page of the tutorial to go to the function reference.
