### ISSUE TITLE
need ability to put in json queries in query string

### ISSUE THREAD

**Issue by yehosef** [elastic/timelion#44]
We often use children documents for our queries. While I'd love to see support for this, it might be a rare use case and/or complicated.  An alternative that would help us and problems solve other use-cases would be to support json in the query string.

In kibana I can put this in the query string
{"query": {"match_all": {}}}
and it works
but in timelion it doesn't.  If I could at least put my query that would help.

**Comment by rashidkpc** [comment]
This probably won't happen, timelion uses lucene query string, which doesn't support parent child and adding support for JSON is sort of a hack in Kibana, not something I want in Timelion
