### ISSUE TITLE
timelion is not using kibana server.basePath config

### ISSUE THREAD

**Issue by TinLe** [elastic/timelion#45]
Currently timelion is making AJAX request to webroot, it's ignoring the configured server.basePath in kibana.yml config file.

This make it not work if kibana is behind proxies.   We have ours behind multiple proxies.

Example, we have kibana at https://logs.example.com/shared/datacenter1/app/kibana and this work fine with server.basePath set to /shared/datacenter1.

But https://logs.example.com/shared/datacenter1/app/timelion will generate errors as timelion is making requests (POST/GET) to webroot, e.g. to https://logs.example.com/ directly.

This is very similar to another bug I reported for Marvel v2.1.1

This is the latest released timelion from Elastic repository, installed via plugin -install command

**Comment by selganor74** [comment]
Yes, I've found the same issue. Chrome was reporting a lot of 404 not found errors. In my setup kibana is reverse proxied from http://hostname.domain/kibana4. The reverse proxy also redirects the / path to http://hostname.domain/default causing lot of 404 errors trying to access http://hostname.domain/default/... for both js scripts and ajax requests.

**Comment by selganor74** [comment]
I have a dirty workaround for the issue. Simply I have redirected http://hostname.domain/timelion/ to http://kibanaserver.domain:5601/timelion/ this seems to fix all the issues...

My config file for apache looks like this:

    [...]
    ProxyPass /timelion/ http://kibanaserver.domain:5601/timelion/
    ProxyPassReverse /timelion/ http://kibanaserver.domain:5601/timelion/

    ProxyPass /kibana4/ http://kibanaserver.domain:5601/
    ProxyPassReverse /kibana4/ http://kibanaserver.domain:5601/
    [...]

**Comment by TinLe** [comment]
Unfortunately, it's not possible to hack a solution when there are multiple proxies in front and some of them you don't control :-(

I've got it to work via port forwarding and nginx rewrites, e.g. ssh direct to the node running kibana4 and timelion.  This is fine for testing purposes, but not for rolling out to production.

**Comment by pemontto** [comment]
:+1:

**Comment by selganor74** [comment]
Of course, mine was just a "dirty" workaround, but let me say, @TinLe,  yours was way long dirtier :-) .
