### ISSUE TITLE
Multi-value Aggregations

### ISSUE THREAD

**Issue by cschwartz** [elastic/timelion#46]
Hi,

I'm interested in using the percentiles aggregation in timelion, however due to it's multi-value nature this seems to not be supported yet.
Is there anything planned in this regard in the future?

I've got a running version at c1f70f50d3911ced28b99db35373181cf9963f55 however I'm a bit hesitant to open a pull request, as this is probably too quick a hack (and not general enough to support all multi-value aggregations, e.g. stats) to get included.
This would allow a query of the form ``.es('*',metric='percentiles:response_time,value='99.0')`` to get the 99% percentiles of a response_time field.

Any suggestions how we could get a similar feature included?

Best,
  Christian

(And btw: Thanks for working on this, this is exactly what I wanted out of kibana for a long time)

**Comment by rashidkpc** [comment]
I've been back and forth on how to do multi value aggs, or really any metric agg that takes parameters. I'm open to ideas. I've never really liked the string parsing for the current `metric` parameter of the `.es()` function

**Comment by carlosvega** [comment]
+100000

**Comment by swturner33** [comment]
+1

**Comment by rashidkpc** [comment]
Still open to ideas, metric aggs with parameters, still not sure on format. It would be introducing a weird argument-within-an-argument thing. I'm not against the feature, I'm just a bit stuck on symantics.

**Comment by rashidkpc** [comment]
I'm going to move this over to this ticket: https://github.com/elastic/timelion/issues/121
