### ISSUE TITLE
Accessing TimeLion App thorugh Kibana UI, gave a blank page on 2.2 build

### ISSUE THREAD

**Issue by rasroh** [elastic/timelion#49]
Kibana build: 4.4
Shield: 2.2.0 snapshot build
Installed Kibana Shield plugin using these instructions here: Install instructions: https://github.com/elastic/x-plugins/blob/master/kibana/shield/README.md

Installed Sense and timelion plugins as well.
``` 
./bin/kibana plugin -i elastic/sense
./bin/kibana plugin -i elastic/timelion
```

Once UI is up and running , I accessed the timelion app through it, and encountered a ```blank page```. Had logged in as es_admin ( with all admin privilages) my ```kibana.yml``` had the basic auth info whom I was logging in as. 

Even if my user whom I had logged in as didn't have the required permissions, it didn't give me any error message, just a blank page. 

<img width="1414" alt="screen shot 2016-01-21 at 3 14 17 pm" src="https://cloud.githubusercontent.com/assets/11466284/12497619/b842f214-c051-11e5-9dec-32aeea14691d.png">

**Comment by rashidkpc** [comment]
This is known, the current released version is 4.3 compatible

Master works with 4.4. This was fixed here: https://github.com/elastic/timelion/commit/a0af8066a705932cb347b786205d2658c3a7f451
