### ISSUE TITLE
How to share the sheet without the query box.

### ISSUE THREAD

**Issue by lavaalone** [elastic/timelion#50]
I have a feeling that i'm missing something very obvious. But still i can not find a way to share the sheets, like feature "Share" on Kibana.

Currently i can add the 'embed' value in the url link but it only partially hides the navigation bars, not all of it.

![image](https://cloud.githubusercontent.com/assets/4546957/12529898/ff2a2a92-c1fc-11e5-94cd-a1c99c9d761c.png)

I'm in production environment so it's very necessary to share the sheet without letting anyone editing it.

**Comment by mwerks11** [comment]
+1

**Comment by mbertani** [comment]
+1
