### ISSUE TITLE
mapper [version] cannot be changed from type [long] to [int]

### ISSUE THREAD

**Issue by dadoonet** [elastic/timelion#51]
Here is my case.

I already have an existing `.kibana` index which contains "old" data. "Old" here means created with elasticsearch 2.0 or 2.1.

When I start Timelion, I'm getting a blank page.

<img width="1058" alt="kibana google chrome aujourd hui at 09 29 54" src="https://cloud.githubusercontent.com/assets/274222/12545890/369235fc-c346-11e5-9236-d2f6e32e93f0.png">

I guess I could fix that with the following procedure:

* export documents in `.kibana` index to disk
* remove my `.kibana` index
* restart Kibana and Timelion
* reimport old data
 
I think that we should try to catch such an error instead of displaying a blank page.

**Comment by rashidkpc** [comment]
This was a bug in Kibana, it should be fixed now
