### ISSUE TITLE
unable to resize charts

### ISSUE THREAD

**Issue by tomryanx** [elastic/timelion#52]
Loving Timelion!

But I can't resize a chart - where's the magic button?  I've tried Chrome on OSX and Windows, but all my charts remain little.

![image](https://cloud.githubusercontent.com/assets/10695410/12661196/4b563294-c66c-11e5-8cfb-385e3187fcb2.png)

**Comment by rashidkpc** [comment]
Click the little gear icon and select how many rows and columns you want
