### ISSUE TITLE
Trouble installing timelion

### ISSUE THREAD

**Issue by xinlintan** [elastic/timelion#53]
Hi, after reading the timelion blog post i tried to install it on my kibana using the following command: 
./bin/kibana plugin -i kibana/timelion

However I keep getting the "Error extracting plugin archive" message. Is there a workaround for this? Thank you.

[root@localhost kibana]# ./bin/kibana plugin -i kibana/timelion
Installing timelion
Attempting to transfer from https://download.elastic.co/kibana/timelion/timelion-latest.tar.gz
Transferring 3381940 bytes....................
Transfer complete
Extracting plugin archive
Error: incorrect header check
Plugin installation was unsuccessful due to error "Error extracting plugin archive"

**Comment by tomryanx** [comment]
What version of Kibana are you running?

**Comment by xinlintan** [comment]
Hi, I am using the latest kibana 5.0.0-snapshot, downloaded here

**Comment by rashidkpc** [comment]
5.0.0 snapshot isn't currently supported. KIbana requires the latest released version of Kibana, Kibana 5.0.0 has not been released.
