### ISSUE TITLE
Problem to graph and other questions

### ISSUE THREAD

**Issue by pittoch** [elastic/timelion#54]
I own an index called " logstash_sto " composed of the columns "Date ; Bay ; ResponseTime ; IOs " 
I try to draw the response time foreach Bay. 
I try this:
.es (index = logstash_stoz3 , timefield = @ timestamp) , .es ( metric = ' avg: ResponseTime ') lines () label ( ResponseTime ).
How I can do this command with one line per Bay ?

I have others questions:
1. how I can compare every first Tuesday of the month?
2. and how I can project ( predictive ) the line in the next 6 months ?

Is there a more explicit support that help to use Timelion ? . I have some difficults to apprehend the product.

Thanks!

**Comment by rashidkpc** [comment]
Please join us on freenode with questions, we reserve github for bug reports and feature request
