### ISSUE TITLE
timelion issues after upgrade to  Kibana 4.5.0

### ISSUE THREAD

**Issue by xo4n** [elastic/timelion#55]
He have upgraded Kibana to 
```
Version  4.5.0-snapshot
Build	9679
Commit SHA	54bcab0
```
and timelion became unusable, all that shows is the header and an empty body
```
<div class="application tab--none-" ng-class="'tab-' + chrome.getActiveTabId('-none-') + ' ' + chrome.getApplicationClasses()" ng-view=""></div>
```

**Comment by rashidkpc** [comment]
4.5.0 is not released. The currently release is 4.3.0. Timelion requires the latest released version.

**Comment by jhenry82** [comment]
Can this issue be reopened? Kibana 4.5 was officially released in March, and Timelion still does not work properly with it. Same behavior as described by @xo4n, just a Timelion header and a blank body.

**Comment by jhenry82** [comment]
Sorry, apparently not the same issue. It has something to do with the fact that we're running Kibana behind a load balancer VIP. If I hit the server directly, it works fine. Kibana works in this setup, but for some reason, Timelion does not.
