### ISSUE TITLE
Make title 'Timelion - Kibana'

### ISSUE THREAD

**Issue by LeeDr** [elastic/timelion#56]
Reference Marvel issue https://github.com/elastic/x-plugins/issues/1432
I suggest Timelion set it's title to ```Timelion - Kibana``` to be consistent.  At the moment it just shows ```Kibana```

![kibanatabs](https://cloud.githubusercontent.com/assets/13542669/12756980/b1ca05a0-c99b-11e5-9f0a-92e0a7d2f224.PNG)

**Comment by rashidkpc** [comment]
Done here: https://github.com/elastic/timelion/pull/58
