### ISSUE TITLE
document seriesList refs

### ISSUE THREAD

**Issue by tomryanx** [elastic/timelion#60]
I want to draw hits, moving average, moving standard deviation, and moving average with multiples of standard deviation added to it.  Simplified examples here for clarity, showing better (hopefully) what I'm trying to do, at the expense perhaps of why I'm trying to do it.

This works:

    .es(), .es().movingstd(7), .es().movingaverage(7)

And I can do this:

    .es().movingstd(7).multiply(3).add(.es().movingaverage(7))

Or altogether:

    .es(), .es().movingstd(7), .es().movingaverage(7), .es().movingstd(7).multiply(3).add(.es().movingaverage(7))

We have a lot of data, so it would be great to avoid querying the same thing multiple times.  Therefore what I would like to do, which seems possible, but I can't figure out how, is something like this:

    .es(), .es().movingstd(7).hide(), .es().movingaverage(7), .timeseries(2).multiply(3).add(.timeseries(3))

It would be great if this was documented either in the tutorial or in the function help.

**Comment by rashidkpc** [comment]
> We have a lot of data, so it would be great to avoid querying the same thing multiple times. Therefore what I would like to do, which seems possible, but I can't figure out how, is something like this:

For what its worth, Timelion already de-dupes data sources, so its not being queried multiple times.

**Comment by tomryanx** [comment]
Ah brilliant!  Thanks for answering.
