### ISSUE TITLE
cusum is named as derivative

### ISSUE THREAD

**Issue by spinscale** [elastic/timelion#61]
Might be a misinterpretation on my side, but it looks as if https://github.com/elastic/timelion/blob/master/series_functions/cusum.js is named derivate and the (see the `new Chainable` call) and the description is also taken from there

**Comment by spinscale** [comment]
The same applies to https://github.com/elastic/timelion/blob/master/series_functions/min.js (named max).

**Comment by rashidkpc** [comment]
woops, thanks!
