### ISSUE TITLE
Timelion does not load

### ISSUE THREAD

**Issue by vgondil** [elastic/timelion#62]
Present Kibana version:4.3.0.

Installed timelion using instructions from: https://www.elastic.co/blog/timelion-timeline.
Installation succeded.

> [root@elk201 kibana]# ./bin/kibana plugin -i kibana/timelion
> Installing timelion
> Attempting to extract from https://download.elastic.co/kibana/timelion/timelion-latest.tar.gz
> Downloading 3383206 bytes....................
> Extraction complete
> Optimizing and caching browser bundles...
> Plugin installation complete

Restarted Kibana. The "Apps" icon now shows next to the Settings option. When I click on it, I can see "Kibana" and "Timelion". However, when I click on Timelion, I see the following error:

```
Fatal Error
Uncaught TypeError: __webpack_require__(...).enable is not a function (http://192.168.254.201:5601/bundles/timelion.bundle.js:53400)
Version: 4.3.0
Build: 9369
Error: Uncaught TypeError: __webpack_require__(...).enable is not a function (http://192.168.254.201:5601/bundles/timelion.bundle.js:53400)
    at window.onerror (http://192.168.254.201:5601/bundles/commons.bundle.js:65224:25)

```
How can I resolve this error?

**Comment by atlgeek007** [comment]
I'm having the same error with version 4.3.1

**Comment by PhaedrusTheGreek** [comment]
Confirmed under 4.3.1

Also discussed here: https://discuss.elastic.co/t/timelion-app-does-not-load/40863

**Comment by rashidkpc** [comment]
Kibana 4.4 was released yesterday. Timelion always requires the latest version of Kibana. See here if you need a 4.3 compatible version: https://twitter.com/rashidkpc/status/694577046937186304

**Comment by vgondil** [comment]
Works! Thank you!

**Comment by gspkibana** [comment]
I am getting the same error. I have the latest version of kibana. [Did a git pull, deleted node_modules dir, npm install]

 Fatal Error
Uncaught TypeError: __webpack_require__(...).setBrand(...).setTabs is not a function (https://localhost:5601/lgd/bundles/timelion.bundle.js?v=8467:104506)

Version: 5.0.0-alpha5
Build: 8467
Error: Uncaught TypeError: __webpack_require__(...).setBrand(...).setTabs is not a function (https://localhost:5601/lgd/bundles/timelion.bundle.js?v=8467:104506)
    at window.onerror (https://localhost:5601/lgd/bundles/commons.bundle.js?v=8467:61666:23)
