### ISSUE TITLE
ShowIfGreater function

### ISSUE THREAD

**Issue by sandeeptakhar** [elastic/timelion#64]
Hi. 

Zach wrote a really nice piece here (this is part 2 of it):

https://www.elastic.co/blog/implementing-a-statistical-anomaly-detector-part-2

He uses a custom showIfGreater() function.  Can we add it to the main stream?

Here is from the post:

The custom movingstd() and showifgreater() Timelion functions can be found here.  Shut down Kibana, add the functions to your Timelion source (kibana/installedPlugins/timelion/series_functions/<function_name>.js), delete the optimized bundle (rm kibana/optimize/bundles/timelion.bundle.js) and restart Kibana.  The functions should be available for use in Timelion now.  Note: Javascript is not my forte, so these are not elegant examples of code :)

https://gist.github.com/polyfractal/5c584f515c4dbd2d5a8f

Also..the steps mentioned..are they the official steps to add in a custom javascript. We had an issue that I will try and reproduce again, but the logs are gone, but apparently adding in custom in that fashion mentioned by Zach doesn't work?

**Comment by rashidkpc** [comment]
You can use the new `condition` function to accomplish this by setting everything less than some number to null: https://github.com/elastic/timelion/blob/master/FUNCTIONS.md#condition
