### ISSUE TITLE
is it possible to provide a title for a chart?

### ISSUE THREAD

**Issue by eben23** [elastic/timelion#69]

**Comment by rashidkpc** [comment]
Nope, but good idea

**Comment by rashidkpc** [comment]
Pushed, you'll need to remove/reinstall to get it.

#### .title()
Adds a title to the top of the plot. If called on more than 1 seriesList the last call will be used.

Argument | Accepts | Description
--- | --- | ---
title | *string* | Title for the plot.

**Comment by eben23** [comment]
thank you very much
