### ISSUE TITLE
Error while trying to access Timelion

### ISSUE THREAD

**Issue by Suren92** [elastic/timelion#70]
I am getting the following error when I trying to access Timelion through Kibana 4.3.1 

Uncaught TypeError: __webpack_require__(...).enable is not a function (http://localhost:5601/bundles/timelion.bundle.js:54356)

Please help!

Thanks.

**Comment by rashidkpc** [comment]
Timelion requires 4.4:

https://github.com/elastic/timelion/blob/master/README.md#installation
