### ISSUE TITLE
get cusum() base when user zoom in

### ISSUE THREAD

**Issue by ConanChou** [elastic/timelion#72]
I am trying to use `cusum()` to figure out user registration over time. I realize that if I zoom into the timeline, the `cusum()` starts over from 0 instead of maintain the original value. That is because I didn't set the `$base`. Then I try to figure out the sum before current scale window. I didn't see any way we can actually use UI data (in this case, the start date user chose) in the document, so that I could use the UI data to do dynamic query against elasticsearch. 

My current query is like: 

```
.es(user_registered).cusum().label(Cumulative)
```

Anyone has any suggestion to solve this issue? Thanks

**Comment by rashidkpc** [comment]
There's really no way to solve this currently, requests are stateless and don't know anything about the previous request

**Comment by rashidkpc** [comment]
Closing this because its not practical, we simply don't have that data
