### ISSUE TITLE
Overlapping axis labels for certain time intervals

### ISSUE THREAD

**Issue by tbragin** [elastic/timelion#73]
Sometimes I see overlapping axis labels (see screenshots)

<img width="1440" alt="screen shot 2016-03-05 at 1 55 19 pm" src="https://cloud.githubusercontent.com/assets/933397/13550778/2204d42e-e2da-11e5-9d7d-b5b48f228733.png">
<img width="1440" alt="screen shot 2016-03-05 at 1 56 28 pm" src="https://cloud.githubusercontent.com/assets/933397/13550779/220671b2-e2da-11e5-8cbc-5bcc4c0eaef7.png">

**Comment by rashidkpc** [comment]
Yeah, I've noticed this too, tbh I'm not super concerned about fixing it. It probably wouldn't be hard using a simple calculation based on the width of the plot combined with https://github.com/flot/flot/blob/master/API.md#customizing-the-axes

**Comment by rashidkpc** [comment]
This should be fixed. Oddly enough with the timezone changes. I had to implement entirely new logic for the axis ticks and that seems to have fixed this.
