### ISSUE TITLE
Resizing glitch when including Timelion charts in Kibana dashboard

### ISSUE THREAD

**Issue by tbragin** [elastic/timelion#74]
Very minor... When I first added a chart to Kibana 4.4.2 snapshot, I resized it but the chart stayed small. Unpon Save / Refresh everything scale as expected. 

<img width="1440" alt="screen shot 2016-03-06 at 8 16 39 am" src="https://cloud.githubusercontent.com/assets/933397/13555382/11ec9564-e374-11e5-97d4-db30187782a2.png">
<img width="1440" alt="screen shot 2016-03-06 at 8 17 08 am" src="https://cloud.githubusercontent.com/assets/933397/13555383/11fdbb8c-e374-11e5-8ce8-6109cafa367b.png">

**Comment by rashidkpc** [comment]
Needs a watcher for the container size. This should be part of the chart directive
