### ISSUE TITLE
Vis plugin dark theme 

### ISSUE THREAD

**Issue by aodj** [elastic/timelion#75]
The (wonderful) new timeseries plugin unfortunately doesn't respect the change to using the dark theme in Kibana:

![screenshot 2016-03-07 13 43 11](https://cloud.githubusercontent.com/assets/1374905/13571215/5d054a58-e46b-11e5-84f5-2e239a6e588e.jpg)

**Comment by rashidkpc** [comment]
No, no it does not. Look at that. Probably an easyish fix

**Comment by tdousset** [comment]
+1

**Comment by quentinlesceller** [comment]
Any update on this matter ?
Thank you !

**Comment by rragin** [comment]
+1

**Comment by tbragin** [comment]
Timelion handling of dark theme seems to have improved in 5.0, but is still not complete:
<img width="930" alt="screen shot 2016-09-12 at 4 08 13 pm" src="https://cloud.githubusercontent.com/assets/933397/18456103/3d05d132-7903-11e6-9b44-2258c70124fa.png">

Now that Timelion is part of Kibana core, opening a new issue there:
https://github.com/elastic/kibana/issues/8239

**Comment by tbragin** [comment]
Timelion is now part of Kibana. This issue has been fixed as part of 5.0 release: https://github.com/elastic/kibana/pull/8336
