### ISSUE TITLE
unable to reduce interval below 1d in timeseries vis

### ISSUE THREAD

**Issue by tomryanx** [elastic/timelion#77]
After setting timepicker to a one week period, with `.es(interval=1d)` 7 data points are displayed, and with `.es(interval=2d)` 4 are displayed, but anything less than 1d appears to be ignored.  For example with `.es(interval=12h)` there are only 7 data points displayed.

How can I get a more granular view?  For example setting the timepicker to a one minute period I see only a single data point - setting the `interval` manually or implicitly (ie leaving it out) doesn't appear to make a difference.

Am I setting it wrong?  The full expression I'm using is eg:

    .es(index=myindex-YYYY.MM.*, interval=12h)

**Comment by rashidkpc** [comment]
Uninstall and reinstall. There's an interval picker now: https://github.com/elastic/timelion/commit/23ab59f9eb54ee404ea991ceb7c937c59cce86c8
