### ISSUE TITLE
Offline build support

### ISSUE THREAD

**Issue by dcode** [elastic/timelion#79]
As a user, I need the ability to install Timelion as a Kibana plugin offline so that I can install it on disconnected systems and/or integrate it into lifecycle management processes (development, testing, production).

This should be similar to how Marvel provides offline install support as a Kibana plugin.

**Comment by dcode** [comment]
Note that instructions for manually building and doing this on my own are sufficient for now.

**Comment by rashidkpc** [comment]
Sold: https://github.com/elastic/timelion/commit/f941d93ccf894262d76038851ddfb8dfb8bb5fc7
