### ISSUE TITLE
Timelion fields with parentheses

### ISSUE THREAD

**Issue by carlosvega** [elastic/timelion#81]
Despite fields with parentheses are valid on Kibana, timelion do not allow it even if they are escaped or enclosed into quotation marks. Could it be fixed? And what about alias of fields, sometimes there are long fields with details about the metric (like if it's on ms or seconds) and could be quite useful to have field alias on elasticsearch or kibana. Like the index alias.

**Comment by rashidkpc** [comment]
Where is it that fields with parentheses are not allowed? Can you post an example query? Screenshot?

**Comment by carlosvega** [comment]
An working example, with no parentheses.
<img width="510" alt="screen shot 2016-03-17 at 20 30 09" src="https://cloud.githubusercontent.com/assets/1414389/13858489/349f9660-ec7f-11e5-8ffe-94ea6828d149.png">

Non working example, with a field with parentheses.
<img width="1162" alt="screen shot 2016-03-17 at 20 32 05" src="https://cloud.githubusercontent.com/assets/1414389/13858525/58889e1e-ec7f-11e5-908d-fdcdf9176b82.png">

Thank you very much in advance.

**Comment by rashidkpc** [comment]
quote the entire value you pass to metric. Does that work?

`.es(metric="avg:duracion_interval(segundos)")`

**Comment by carlosvega** [comment]
Oh ! Why I didn't try that? 😬Sorry ! 😐
I think we could close this issue. 
Thank you! 😀
