### ISSUE TITLE
Externalize configuration files

### ISSUE THREAD

**Issue by seang-es** [elastic/timelion#83]
I've received a request to externalize the timelion.json file so it can be placed outside the timelion directory.  It does not look like this is currently possible.

**Comment by rashidkpc** [comment]
Not currently possible, and I probably won't implement this. The right way to do this is move the timelion configuration to kibana.yml.

**Comment by rashidkpc** [comment]
This is done with the merging of timelion into the Kibana core: https://github.com/elastic/kibana/pull/7994/commits/a1f543417db4e0b33f88cb29adf5bc9dacd7a7f8
