### ISSUE TITLE
Help screen text doesn't show current interval

### ISSUE THREAD

**Issue by LeeDr** [elastic/timelion#85]
This is pretty minor.  On the second page of help text in Timelion (K4.5.0 RC), it says this below;
(my interval was on the default 1d, but it doesn't seem to matter if I change it, the help text says it's 'currently set to .")

"Intervals
You might already have one nice chart, but I'm going to operate on the assumption you don't for educational purposes. The input bar at the top has two inputs. On the left, is your expression, leave that alone for now, we'll get to it. On the right is the interval selector, which is **currently set to .** Set it to 1d. "

![2016-03-24 15_29_50-u14k dashboardpage and test start for beats running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/13542669/14030500/d9fc7a28-f1d5-11e5-872a-f4badb4ecc44.png)

**Comment by rashidkpc** [comment]
Fixed in master

![screen shot 2016-05-06 at 4 31 18 pm](https://cloud.githubusercontent.com/assets/1250387/15088405/02c1002a-13a8-11e6-8612-7b44d4c13e39.png)
