### ISSUE TITLE
Timelion doesn't support any timezone other than the browser's

### ISSUE THREAD

**Issue by ChristinaLy** [elastic/timelion#86]
I used Kibana 4.4.1 to generate a Timeseries visualization, but I found that when I select the timepicker and set a time like "Last 15 Minutes", the time on the x-axis can not match the real time.
The real time of the browser is 16:52.
See picture 1 and picture 2, they are shown at the same time, but the x-axis shows different.
![1](https://cloud.githubusercontent.com/assets/7933348/14069944/134670f4-f4d3-11e5-9d38-5651ec112717.png)
![2](https://cloud.githubusercontent.com/assets/7933348/14069949/1a86bdec-f4d3-11e5-9947-22210547bac4.png)

**Comment by rashidkpc** [comment]
Yep, this is the current situation by design. Timelion currently uses Flot as its charting library and there's some issues with the current support for timezones in the version I'm using.
