### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by nskalis** [elastic/timelion#87]
Hi guys,

I just started using Timelion yesterday, and I have to admit that is looks and behaves awesome.
What I am missing is the ability to use "variables". (I know that the link of Kibana is a template itself.)

But I noticed in the video the use of variables, but I cannot find them documented.
Could you please advise on how can i specify a variable ? And how can I make that variable to take all a value from a list, let's say sth like the output of the terms filter ?

Many Thanks,
Nikos

**Comment by nskalis** [comment]
thanks @m82labs would it be possible `$var` to to be a list also and used for metric ?

more specifically, sth like the following ?
```
$var=['a','b','c'], .es(index='myindex-*',q='name:value', metric=avg:$var)
```

**Comment by m82labs** [comment]
I am pretty sure you can only store strings. So you could do:
```
$var='avg:some_metric',.es(index='myindex-*',q='name:value', metric=$var)
```

If we could use variables within an argument value it would be a game changer for me.

**Comment by rashidkpc** [comment]
I want to stress that variables are not formally implemented.

They're in the grammar and the runner, but they're intentionally omitted from the tutorial as the implementation is minimal and incomplete. There's no string concatenation, no arrays, they can't be used across charts, and lots of other lacking functionality. I don't recommend using them as I may decide to drop them.

**Comment by nskalis** [comment]
thanks @rashidkpc . noted .
