### ISSUE TITLE
Print X-Axis value to timelion label

### ISSUE THREAD

**Issue by Prabusrajan** [elastic/timelion#89]
Hi,

I have just started to use Timelion. I would like to know, how can i display my x-axis coordinates in my label. By default, it just prints the y axis coordinates.

Also, i see only max 12 labels in the X-axis, is there a way to increase it. Appreciate the Timelion community's advise to achieve my requirement.

Thanks,
Prabu

**Comment by tsegal** [comment]
+1 on the question

**Comment by pagenbag** [comment]
As far as I know its not possible ... but it should be easy enough to add in.

The number of ticks is a simple override on the options.

For the label values , maybe some format string option ? "%y ( %x )"

**Comment by betellen** [comment]
+1 on the question

**Comment by rashidkpc** [comment]
Currently not possible, though I'd take a pull for it.

**Comment by tbragin** [comment]
Timelion is now part of Kibana. A corresponding issue is now being tracked here: https://github.com/elastic/kibana/issues/8948
