### ISSUE TITLE
Help: Calculated Fields

### ISSUE THREAD

**Issue by dubrowgn** [elastic/timelion#90]
I'm sorry if this is written down somewhere. I am new to Timelion, and haven't been able to find much in terms of documentation.

Is it possible to use a calculation of two fields as the value for a metric aggregation? I'm wanting to do something like this:

> sum(count * time) / sum(count)

Where `count` and `time` are from the same record.

Thanks!

**Comment by vinuja** [comment]
+1

**Comment by rashidkpc** [comment]
This isn't supported and can't be simply due to the way timelion works. Timelion is a generic time series processor, so if the upstream data source doesn't support computed fields in its query language, timelion can't either. I assume this is about Elasticsearch, which does not support this.

**Comment by sathibault** [comment]
Elasticsearch supports inline scripts for both filters and aggregations.  
Can't timelion support those?
