### ISSUE TITLE
Specify required version of Kibana

### ISSUE THREAD

**Issue by nplatis** [elastic/timelion#91]
The README mentions that Timelion requires the _latest_ version of Kibana, but unfortunately this statement is rather vague. I believe it would be preferable to mention specifically the version of Kibana needed.

**Comment by xo4n** [comment]
It will be helpful, also where to find versions that work with previous kibana releases, thinking of kibana 4.4, as kibana4.5 requires upgrade to elasticsearch 2.3

**Comment by xo4n** [comment]
It will probably save you also a couple of tickets a month :)
![image](https://cloud.githubusercontent.com/assets/9038651/14560737/d7fbd8ca-0311-11e6-8952-164472ffb067.png)

**Comment by rashidkpc** [comment]
Yeah, still not going to do this. Its an experiment, if and when it moves out of experiment mode, I'll revisit this.
