### ISSUE TITLE
Logo not rendering in K5

### ISSUE THREAD

**Issue by tylersmalley** [elastic/timelion#92]
Tested on Ubuntu 32bit
Firefox 44.0.2
Kibana 5 - alpha1
Timelion 5.0.0-0.1.259

<img width="1266" alt="screenshot 2016-04-04 20 41 20" src="https://cloud.githubusercontent.com/assets/40265/14270724/c885256e-faa5-11e5-89e9-02ae3f4954d5.png">

**Comment by epixa** [comment]
I encountered this as well.  Kibana was set up on Ubuntu 64bit, but I was accessing it from Firefox 45 on OS X.

**Comment by rashidkpc** [comment]
I haven't been able to replicate this. Is it still happening @tylersmalley @epixa ?

**Comment by epixa** [comment]
I saw this happen today on alpha2 darwin, firefox. I can check again tomorrow.

**Comment by rashidkpc** [comment]
Sure enough. How very odd. Something weird with SVGs in firefox maybe? 
![screen shot 2016-04-29 at 7 35 19 am](https://cloud.githubusercontent.com/assets/1250387/14919277/f73f1488-0ddc-11e6-8f06-c59ffe21a7c0.png)

**Comment by rashidkpc** [comment]
Hmmm, firefox sees it as a 0x0 image

![screen shot 2016-04-29 at 7 48 02 am](https://cloud.githubusercontent.com/assets/1250387/14919685/c1360e76-0dde-11e6-822d-89837a2f8434.png)

**Comment by rashidkpc** [comment]
Fixed: https://github.com/elastic/timelion/commit/f12cbe5441d0cd864b2013d4d1f18b226fe8ead7
