### ISSUE TITLE
Holt-Winters not working

### ISSUE THREAD

**Issue by carlosvega** [elastic/timelion#94]
It raises the error: **Invalid array length** when trying to do a forecast with HW like […]**.testcast(3, 0.9)**

[Documentation says](https://github.com/elastic/timelion/blob/master/FUNCTIONS.md#testcast):

> Use holt-winters to forecast values. Basically useless. **I have no idea how this works.**

Couldn't be this documentation more detailed? :confused: I can manage to get it working. Thanks in advance. 

The complete error looks:

> Error:  in cell #1: Invalid array length
>     at throwWithCell (/Users/carlosvega/elastic/kibana/installedPlugins/timelion/handlers/chain_runner.js:28:11)
>     at /Users/carlosvega/elastic/kibana/installedPlugins/timelion/handlers/chain_runner.js:181:11
>     at bound (domain.js:287:14)
>     at runBound (domain.js:300:12)
>     at tryCatcher (/Users/carlosvega/elastic/kibana/node_modules/bluebird/js/main/util.js:26:23)
>     at Promise._settlePromiseFromHandler (/Users/carlosvega/elastic/kibana/node_modules/bluebird/js/main/promise.js:503:31)
>     at Promise._settlePromiseAt (/Users/carlosvega/elastic/kibana/node_modules/bluebird/js/main/promise.js:577:18)
>     at Promise._settlePromises (/Users/carlosvega/elastic/kibana/node_modules/bluebird/js/main/promise.js:693:14)
>     at Async._drainQueue (/Users/carlosvega/elastic/kibana/node_modules/bluebird/js/main/async.js:123:16)
>     at Async._drainQueues (/Users/carlosvega/elastic/kibana/node_modules/bluebird/js/main/async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate] (/Users/carlosvega/elastic/kibana/node_modules/bluebird/js/main/async.js:15:14)
>     at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by rashidkpc** [comment]
As noted in the docs, this function was basically useless, so I've removed it: https://github.com/elastic/timelion/commit/4d554a170b2b9121bc0bac730dc102cf80a0c256
