### ISSUE TITLE
Calculate ratio from count of occurrence of text fields

### ISSUE THREAD

**Issue by JeremyColton** [elastic/timelion#96]
Hi, I collect many events from websites and visualize them using Kibana. The events include page loaded", "image clicked". My Kibana index contains an 'event' field that stores these event text values.

I want to show a graph of CTR on the images, so:
total "image clicked" events / total number of all events.

Can I do this using TimeLion and if so, how?
What are the 25 different functions that can be used in TimeLion, link?
Can the  resulting visual be added to a regular dashboard with regular visuals from Kibana?

Many thanks.

**Comment by rashidkpc** [comment]
Count all docs with "clicked" in the `event` field, divide by count of all docs: 

`.es(q="event:clicked").divide(.es(q="*"))`

Function reference here: https://github.com/elastic/timelion/blob/master/FUNCTIONS.md

You can add stuff to the dashboard by going to teh "visualize" tab in Kibana and choosing the **timeseries** visualization which will let you use timelion expressions to create a savable dashboard panel

If you have other support questions please ask on http://discuss.elastic.co, I save github for feature request and bug reports

**Comment by calexicoz** [comment]
Recently, "split" was introduced (thanks! that's awesome). It would be nice (ie this is a feature request) to be able to use "split" with divide somehow. Example :

```
.es(q="event:clicked",split="country:5").divide(.es(q="event:served",split="country:5"))
```

Basically the ability to do calculations on multiple groups at the same time. I know you can already do this is in the same graph by doing multiple queries. Doing it in one call would be a nice convenience though, and would avoid a lot of repetition. There is an underlying issue there: the top 5 for served is not necessarily the top 5 for clicks. Not sure what would be the best way to solve that given the existing syntax.

I guess that #31 will make this less of an issue, but I've definitely been missing this.
